### ISSUE TITLE
adding Qz-tray to ionic react project via npm

### ISSUE THREAD

**Issue by savageqm** [qzind/tray#1045]
I added the Qz-tray using npm install qz-tray and then declared
`import * as qz from 'qz-tray';`  but I can't compile because it complains about qz-tray not finding the declaration.  Is the qz-tray compatible with the Ionic react framework(typeScript)? .  I added a index.d.ts file to the qz-tray folder, while that remove the error it still did not compile as it complained it could not find the path. I'm not using webpack for the ionic react project.

`[react-scripts] ERROR in ./node_modules/qz-tray/qz-tray.js 621:10-33
[react-scripts] Module not found: Error: Can't resolve 'path' in 'xxxxx/node_modules/qz-tray'
[react-scripts] BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.`

**Comment by tresf** [comment]
> Error: Can't resolve 'path'

I believe this to be the actual error and "Module not found" is a bit misleading of a message here.

If this is the same as I've received in the past, from our [api-overrides](https://github.com/qzind/tray/wiki/API-Overrides/) section:

> Add the following entry to your `package.json` to omit path from AOT compilation:
>
> ```json
> "browser": { "path": false }
> ```

We use [`'path'`](https://github.com/qzind/tray/blob/1e2c0855511a3d2c62cedb9225678a6521660050/js/qz-tray.js#L672) to handle relative URL calculations.  If there's a better way to handle this, we'd welcome some advice.

> Is the qz-tray compatible with the Ionic react framework(typeScript)?

QZ Tray is a JavaScript library first and foremost.  We've had luck importing it into TypeScript, but it's not a TypeScript module (and likely never will be).   It could likely be batched into one, since we try to label our API calls with JSDoc comments which infer type declarations, but [last I tried this (e.g. using `tsd-jsdoc`), it wasn't straightforward](https://github.com/qzind/tray/issues/890#issuecomment-1006830756).  If you or someone you know would like to incorporate something like this into our build system, it would be welcome.

**Comment by kgherrmann** [comment]
Did anyone fine a solution for this. adding `"browser": { "path": false }`

I also tried adding a fallback with no avail:
` fallback: {
        path: require.resolve("path-browserify"),
      },`

Any and all recommendation welcome!

**Comment by smeakin** [comment]
We ran into this same issue, and tried adding `"browser": { "path": false }` to our `package.json` file didn't fix the issue. I tried adding it to the `package.json` of this module in the `node_modules` folder and that fixed the issue for us.

For context, we're running a vue application, which may or may not explain why that particular method worked for us.

**Comment by tresf** [comment]
<details>
<summary>Click to show deleted comment</summary>

> We ran into this same issue, and tried adding "browser": { "path": false } to our package.json file didn't fix the issue. I tried adding it to the package.json of this module in the node_modules folder and that fixed the issue for us.
> 
> For context, we're running a vue application, which may or may not explain why that particular method worked for us.

</details>

@smeakin sorry for the necromancy, but I received the above email notification and wanted to see if the proposed solution, or your own version helped.

**Comment by smeakin** [comment]
@tresf No worries! We ended up finding out that our webpack file wasn't being read correctly, when we fixed that we were able to add the following to it, which resolved the issue.

```
resolve: {
  fallback: {
    path: false
 }
}
```

**Comment by tresf** [comment]
Thanks! 

Our code tries to fallback on Node's `path`  when not being run in a browser:
https://github.com/qzind/tray/blob/8816df208300a9373a2a120a12cdfc69fec5a439/js/qz-tray.js#L665-L675

... this is because we want to support relative URLs and it's the best way we know how when we don't have access to the browser.

Unfortunately, this causes grief because (as far as I understand) the JavaScript frameworks attempt to compile this `require('path')`, despite the target browser never getting into this conditional.  It's actually quite rare that our library is run directly in Node to communicate with QZ Tray. 

In Java-land, we'd try to tackle this type of undefined reference problem with various weak linking techniques.... but I'm just not sure how to do the same for ReactJS.

I welcome any ways to handle this better if you or someone you knows is familiar with such a problem.

The best article I've seen about this issue is herem which took days of searching to find: https://stackoverflow.com/questions/50202948/

**Comment by smeakin** [comment]
Thanks for explaining!

Sadly I'm not super familiar with the issue, all I can really offer is that `"browser": { "path": false }` in your package's `package.json` file seemed to the fix the issue the first time.

I think that makes sense as adding that line should then provide a resolution to the `require('path')` for browser bundles only (to essentially ignore it) and leaving node to resolve `path` properly, which should be fine as a solution if browsers will never reach that code path in the first place and therefore don't need a proper resolution to the require.

**Comment by tresf** [comment]
>  all I can really offer is that `"browser": { "path": false }` in your package's package.json file seemed to the fix the issue the first time.

Done via https://github.com/qzind/tray/commit/be4c4853be1446a62846cebccab73332dc2cef6e.  Hopefully this avoids some pain to others, thanks!
