### ISSUE TITLE
QUESTION: Impementing ThermalPrinterEncoding npm plugin with qz tray

### ISSUE THREAD

**Issue by INARTECHSA** [qzind/tray#1087]
So im trying to use this plugin https://github.com/NielsLeenheer/ThermalPrinterEncoder and what I do is:
```
let encoder = new ThermalPrinterEncoder({
          language: 'esc-pos'
        });
let encodeddata = encoder
          .initialize()
          .size('normal')
          .align('center')
          .text('TEST')
          .encode();
```
This code returns an array of Uint8Array. And I have this config for qz:
```
let config = qz.configs.create("POS-58-Series", { encoding: 'Cp869' });
let data = [
  ??????
];
return qz.print(config, data);
```
How can I use the encoding result as printing data? Thanks!

**Comment by tresf** [comment]
Hi, thanks for asking.  [NielsLeenheer/ThermalPrinterEncoder](https://github.com/NielsLeenheer/ThermalPrinterEncoder) is a very popular project for ESC/POS or Star Line Mode printing and I'm glad that you've asked about it here.

We do not (yet) have any examples for using this library directly with QZ Tray.  I will ping our developer @bberenz for a feature request to natively support `Uint8Array` in a future version. :)

I would recommend that you do one of the following:
* Convert the `Uint8Array` into [hex](https://qz.io/docs/raw#hex)<br>--OR--
* Convert the `Uint8Array` into [base64](https://qz.io/docs/raw#base64)

JavaScript is not very good about raw bytes because most native libraries want to convert these to UTF8, which will break things.

I have not tested this yet, but here is a library I have found which might be capable of converting `Uint8Array` to base64: 
https://gist.github.com/enepomnyaschih/72c423f727d395eeaa09697058238727

Please share the solution that you use, we will leave this bug report open.

**Comment by tresf** [comment]
@INARTECHSA while you await native `Uint8Array` support, I've prepared an example using Node's hex conversion here:

https://gist.github.com/tresf/dc922a16e0f56519e975a3e26315ea56

We'll track the `Uint8Array` over at #1088.

**Comment by tresf** [comment]
> 

Update: `Uint8Array` support has been added via #1098.
