### ISSUE TITLE
Unsupported WebSocket version detected: HyBi-00/Hixie-76

### ISSUE THREAD

**Issue by Bhavesh27** [qzind/tray#1094]
Getting Unsupported WebSocket version detected: HyBi-00/Hixie-76 error in the connect method most of the times.
This issue started occuring recently only after the release of v2.2.2.  We didn't changed anything on our side
The qz-tray.js version we are using is 2.0.10

Has anybody else also faced why it is failing for the users with the above error.

**Comment by tresf** [comment]
This is generally a sign that the `Websocket` version offered by the browser is malfunctioning.

Here's the code:
https://github.com/qzind/tray/blob/22de1eee796ddb77de12ea9e157208f21851eb82/js/qz-tray.js#L1109-L1115

It's been a while since we've seen this issue, but the two scenarios we've seen are:
* Old browser versions that do not implement full Websocket support (rare and only happened with very old versions of Safari)
* JavaScript library which mutates the native `Websocket` object.  Possible related: https://stackoverflow.com/a/61067500/3196753

Can you test https://demo.qz.io on the same workstations and see if they exhibit a problem?  You may also want to investigate the following:
* Check if `setWebSocketType` is being called in code
* Debug this line: https://github.com/qzind/tray/blob/22de1eee796ddb77de12ea9e157208f21851eb82/js/qz-tray.js#L651

**Comment by tresf** [comment]
> The qz-tray.js version we are using is 2.0.10

This is peculiar.  Is there a chance your old version of qz-tray.js was modified from its original?  The above two code blocks are identical since v2.0.10, here's the old version: https://github.com/qzind/tray/blob/v2.0.10/js/qz-tray.js

**Comment by Bhavesh27** [comment]
Hi Tres,

Our qz-tray.js file is not modified and points to original 2.0.10.
Apart from that we released no new changes in QZ Tray module as well with contains all intialization code.

We too never faced this issue but since few days users are continuously complaining of facing this issue. I am able to replicate the same in my local setup as well.

Solutions which i tried out and tested in my local setup:-
1. Upgraded qz-tray.js from 2.0.10 to 2.2.2 version, yet same issue came
2. Used `qz.api.setWebSocketType(require('websocket').w3cwebsocket);` - Still faced same face
3. Used `QZTray.api.setWebSocketType(require('ws'));` - Still faced same issue
4. Tried previous version v2.1.4 of QZ Tray software to check if it is happening for only v2.2.2 or not. Faced same issue with v2.1.4 as well on local setup.

All these testing was done on Chrome Version 109.0.5414.87 (Official Build) (x86_64) as most of our users are on Chrome.

Lastly i tried https://demo.qz.io/ there. I was able to successfully connect and it showed connection Active.  I am attaching our implementation of the intialization of web socket.
`
if (QZTray.websocket.isActive()) {
      this.currentQZStatus = {
        error: false,
        message: this.printingErrorMessages.CONNECTED.msg,
      };
      resolve(this.currentQZStatus);
    } else {
      QZTray.websocket.connect(qzConfig).then(() => {
        resolve({
          error: false,
          message: this.printingErrorMessages.CONNECTED.msg,
        });
      }).catch((error) => {
        console.log(error);
        reject({
          error: true,
          message: this.printingErrorMessages.NOT_CONNECTED.msg,
        });
      });
    }
`

**Comment by tresf** [comment]
Thanks for sharing.  By chance do you have any middleware which may be intercepting the websocket traffic (such as proxy, web firewall, etc?). If you visit https://localhost:8181 and view the certificate, is it ours?

**Comment by tresf** [comment]
After investigating this, it appears a polyfill for the Websocket is being used.  We're awaiting word back from @Bhavesh27 on what this is and how this was added.  If I don't hear back in a week's time, I'll close this issue out.

**Comment by tresf** [comment]
Closing due to lack of response.
