### ISSUE TITLE
How can I use Deno crypto to generate a signature for QZ?

### ISSUE THREAD

**Issue by daneofgrandshipper** [qzind/tray#1105]
Is there an example of how we can use Deno to generate a signature QZ tray?

**Comment by tresf** [comment]
If you're using Deno as the back-end for signature generation, here's an example using subtle.crypto, which seems to be the preferred library for Deno.

https://gist.github.com/tresf/432a3f0d52f9dcbe2028b5c8ae749c6d#file-sign-message-deno-js

This could probably be simplified using other dependencies (such as forge), but since Deno's decided to implement the browser's native subtle crypto, I've chosen to use these for consistency.  (we don't use these in our examples because of the SSL requirement by the browser, something which Denos  isn't subject to).

If instead you're using the browser to sign messages (or using a mixed backend/front-end configuration) you'll need to adapt our client-side techniques which are available here:
* https://github.com/qzind/tray/wiki/signing-examples#option-2---client-side-signing
* https://github.com/qzind/tray/blob/master/assets/signing/sign-message.js
* https://www.youtube.com/watch?v=X72y6ZZTWzE

**Comment by tresf** [comment]
Closing due to lack of response, I'll assume this question is answered.
