### ISSUE TITLE
Trying to print A5 getting print in the Top Right Corner

### ISSUE THREAD

**Issue by kaisanjay** [qzind/tray#1110]
Hello everyone, I'm trying to print A5 with QZ.
Here is my configuration =>
```
const config = qz.configs.create(printerName, {
        size: {width: 150, height: 210},
        units: 'mm',
        margin: 0,
        scaleContent: true,
        orientation: 'landscape'
      });
```

It is printed in the *** upper right corner *** of the page.
I've experimented with other scaleContent combinations.
![IMG_20230410_183256](https://user-images.githubusercontent.com/16288226/230920449-86ee8b59-933f-4f4d-a6e2-e14268e9c420.jpg)
 such as fit, fill, and stretch are still appearing in the top right corner.
 Can anyone assist me?

**Comment by lite1979** [comment]
Your config shows "orientation: 'landscape'", but your size configuration is "{width: 150, height: 210}", with dimensions that are portrait, not landscape. I believe this is limiting the width of the print results to a width of 150mm instead of the desired 210mm.

I would recommend either omitting the size and orientation configurations altogether and just using "scaleContent: true"
The orientation should automatically match the short edge of the print data to the short edge of the print media, and the print data should be scaled to the page size as defined by the printer driver.

If this does not fix the problem, provide the size config as "{width: 210, height: 150}"

**Comment by kaisanjay** [comment]
Thank you for your response; I'll give it a shot.

**Comment by kaisanjay** [comment]
I tried removing the orientation and size, but it still prints like this.
half of the page is getting printed
![IMG_20230411_152314](https://user-images.githubusercontent.com/16288226/231143049-235c4dee-835d-4007-bff3-57b364bc3f49.jpg)

**Comment by lite1979** [comment]
@kaisanjay 

Would you mind sharing logs? You can email them to me at lite.m.finocchiaro@gmail.com or you can share a gist here on Github if the information is ok to share.

Click QZ-Tray > Advanced > Diagnostic > Zip logs to Desktop, attach in email

or 

Click QZ-Tray > Advanced > Diagnostic > Browse User Folder to see the files yourself

Some more details that are relevant:

Operating System
QZ-Tray version
Printer Make/model and default paper size

Note: There is a bug on MacOS that will swap height for width that affects landscape documents intended for landscape media sizes; we have a fix being tested for this, but it needs some more work before it gets published.

**Comment by tresf** [comment]
```
scaleContent: 'fill',
```

This should be `true` or `false`.

**Comment by tresf** [comment]
Closing due to lack of reply, I'll assume `scaleContent: true` will fix this, but it doesn't or you still need help with this, I'd be happy to reopen.
