### ISSUE TITLE
Issue with printing 8x6 labels

### ISSUE THREAD

**Issue by dkisic** [qzind/tray#1149]
I am having trouble printing the word file attached here. Before I print it out I convert it to pdf and then send it as base64.

Here is the word file:

[APPLE & SPICE #8373-F.docx](https://github.com/qzind/tray/files/11885944/APPLE.SPICE.8373-F.docx)

The word file is 8 x 7.4 and paper in the printer is 9 x 7.

    var options = {
        orientation: 'landscape',
        scaleContent: true,
        units: "in",
        margins: {
            top: 0.25,
            bottom: 0.25,
            left: 0.45,
            right: 0.45
        }
    };

    var config = qz.configs.create(printerName, options);

    var data = [{
        type: 'pixel',
        format: 'pdf',
        flavor: 'base64',
        data: pdfBase64
    }];

    return qz.print(config, data);

With this settings I get it out like this:
![landscape](https://github.com/qzind/tray/assets/32257921/2564b51d-81bc-4067-bd10-fb21a91a74c8)

    var options = {
        orientation: 'portrait',
        scaleContent: true,
        units: "in",
        size: {
            width: 8,
            height: 6
        },
        margins: {
            top: 0.25,
            bottom: 0.25,
            left: 0.45,
            right: 0.45
        }
    };

    var config = qz.configs.create(printerName, options);

    var data = [{
        type: 'pixel',
        format: 'pdf',
        flavor: 'base64',
        data: pdfBase64
    }];

    return qz.print(config, data);

And when I set it to portrait I get it out like this:

![portrait](https://github.com/qzind/tray/assets/32257921/d11170d2-a080-4b3f-836f-8352c2b95c18)

This is how it's supposed to look like:

![correct](https://github.com/qzind/tray/assets/32257921/adb892d5-1592-4328-89e5-73fde1fe54f7)

The logs are here. Printing on EPSON GP-C831

[qz logs.zip](https://github.com/qzind/tray/files/11891294/qz.logs.zip)

Any help would be much appreciated.

**Comment by tresf** [comment]
@dkisic thanks kindly for attaching the logs.   I've converted the Base64 and attached the PDF file that you're printing, since that's what QZ Tray is seeing.

[hazard-statement.pdf](https://github.com/qzind/tray/files/11938556/hazard-statement.pdf)

> word file is `8 x 7.4` and paper in the printer is `9 x 7`

The first thing that I see is that your document size is actually: `8.01 x 6.91`.  When adding margins of `.45, .45` and `.25, .25` to the paper, you'll have a paper size that's effectively `8.1 x 6.5`, so this should fit pretty well:

* Paper: `8.1 x 6.5` (9 - .45 - .45), (7 - .25 - .25)
* Doc: `8.01 x 6.91`

I would expect this to work well.

The second thing I see is that you're using Microsoft Windows.  This is generally a good thing because driver support for printers is generally better on Windows than other platforms.  What I'm curious about is what sizes that the EPSON GP-C831 natively supports? 

The spec page says the following:
* Printable area up to 8.0 x 22"
* Print Resolution: 720 dpi x 720 dpi maximum

If this is correct, I would recommend the following settings:

```js
var options = {
    orientation: 'landscape',
    units: "in",
    size: {
        width: 6,
        height: 8
    }
};

var config = qz.configs.create(printerName, options);

var data = [{
    type: 'pixel',
    format: 'pdf',
    flavor: 'base64',
    data: pdfBase64
}];

return qz.print(config, data);
```

However, I'm still unsure about a height of `8`.  Can you check the following:
* Run (Windows Key + R)
* `control printers`
* Find the EPSON GP-C831, click once on it
* At the top of the Window, click "Print Server Properties"
* Look for a form on the "Forms" tab that most closely matches your paper
* If a form does not exist that closely matches your paper, please create it with length dimensions that are the same as your paper.

If this does not work, delete the newly created form and look inside the Epson device driver for default settings related to paper size and orientation.  This is often inside an area called "Printer Properties, Preferences" or "Printer Properties, Advanced, Printing Preferences".

On occasion, the driver will ignore the page size provided by our application and a manual configuration is needed.

If none of this works, email us at support@qz.io and we'll setup a screenshare to investigate more.

**Comment by tresf** [comment]
@dkisic hi, checking in on the above.

**Comment by tresf** [comment]
@dkisic checking in again before we close.

**Comment by dkisic** [comment]
Hello,

unfortunately I wasn't able to reproduce all the steps you mentioned cause the printer stopped working in the meantime. This were the latest options and we came close with that:

```
var options = {
    orientation: 'portrait',
    units: "in",
    size: {
        width: 7,
        height: 9
    },
    margins: {
        top: 0,
        bottom: 0,
        left: 0,
        right: 0
    }
};

var config = qz.configs.create(printerName, options);

var data = [{
    type: 'pixel',
    format: 'pdf',
    flavor: 'base64',
    data: pdfBase64
}];
```

return qz.print(config, data);
![7_7x9_only_left](https://github.com/qzind/tray/assets/32257921/af6e1b27-606a-4a9e-8477-adcc9678f030)

**Comment by tresf** [comment]
I'm sorry that the printer died.  Do you plan on replacing it and continuing this effort?  If so, we'd happily leave this bug report open.

**Comment by dkisic** [comment]
Yes, we're going to replace it. I'll let you know once it's sorted out. Thanks for the patience.

**Comment by tresf** [comment]
It looks like part of this conversation will be taken offline.  I'll do my best to come back here to report any fixes as we find them.

**Comment by lite1979** [comment]
@dkisic Thanks for arranging a video conference with the client and this hardware. We found out that there was a custom 8x7 inch paper size being used. This took some time to track down, but after removing the QZ size and orientation parameters, the base64 PDF print result is now acceptable for the client.
