### ISSUE TITLE
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL

### ISSUE THREAD

**Issue by PhamChuongBD** [qzind/tray#1154]
The URL works when I view it in the browser, but when I print it using QZ, it returns a 403 error. How can I fix this issue with QZ? Thank you

**Comment by tresf** [comment]
@PhamChuongBD 403 means that Java cannot access this URL.  This may be due to a proxy or firewall on the PC which Java cannot communicate through.

Can you please update qz-tray.js to beta here: https://raw.githubusercontent.com/qzind/tray/master/js/qz-tray.js

... and then try to use a technique similar to this:

```js
fetch("https://files.onpoint.vn/order/2023/07/06/RXCJ28EXO7_shipping_label.pdf").then((response) => {
      if (!response.ok) {
        throw new Error(`HTTP error, status = ${response.status}`);
      }
      return response.arrayBuffer();
}).then(buffer => {
    var config = qz.configs.create("PDF");
    return qz.print(config, [{ type: 'pixel', format: 'pdf', flavor: 'base64', data: new Uint8Array(buffer) }]);
});
```
