### ISSUE TITLE
Error in app that does not use QZ Tray

### ISSUE THREAD

**Issue by poul0004** [qzind/tray#1201]
Hello-
On a Win 10 Pro workstation with QZ Tray 2.2.2+1 deployed.  Our shipper uses QZ to generate shipping labels from their website.  QZ is configured as a Start Up app.

This workstation also runs other productivity applications.  After a reboot, I run a desktop application that is not designed to use QZ Tray.  When selecting a report in this application, I get presented with an html page that is used to set parameters and filters to generate a PDF report.  The html page uses both java script and VBScript.  

With QZ Tray running, I get errors when this html filter page is being loaded by the application.  I get errors related to assigning an ondblclick procedure and calling other functions, such as SetFocus as the page loads.  The html filter page does not load properly, and I cannot generate reports.

A workaround is to exit the desktop application with the script error.  Exit QZ Tray.  Relaunch QZ Tray.  Relaunch the desktop application.  At this point the desktop application works as expected.

This issue began after installing QZ Tray 2.2.2+1.

I'm looking for a fix so I don't have to exit and relaunch QZ Tray to use my productivity app.  I'm also concerned that other applications that use java script or VB script may experience similar errors.
TIA

**Comment by tresf** [comment]
Can you please provide logs from this other application?  I'm not sure how QZ Tray can interfere with a 3rd party application, but if it's using JavaScript and VBScript, I'm hoping that there are some usable logs that I can use to infer the cause.

QZ Tray is a desktop application that listens on https://localhost:8181, so there's a chance that your 3rd party application uses this same port and the issue is a port conflict.  If this is the case, you could prevent QZ Tray from loading on boot and QZ Tray will automatically fallback to port 8282, however this is just a speculation.

**Comment by tresf** [comment]
Also, if you'd like to email support@qz.io, I'd be happy to take a first hand look.

**Comment by tresf** [comment]
No response in two days, closing.  Please reach out via email so that we can take a firsthand look at this.
