### ISSUE TITLE
Injects potentially malicious cert. Persistant after uninstall.

### ISSUE THREAD

**Issue by prk0ghy** [qzind/tray#1268]
defaults read /Library/Preferences/org.mozilla.firefox
{
    Certificates =     {
        Comment = "Enterprise policy installed by QZ Tray on 2024-04-04T17:19Z";
        ImportEnterpriseRoots = 1;
    };
    EnterprisePoliciesEnabled = 1;
}

**Comment by tresf** [comment]
It's required for browser communication.  Uninstall the software if you have a problem with it.

**Comment by prk0ghy** [comment]
It persisted after uninstall, this is why I raised the issue.

**Comment by tresf** [comment]
There's two things here:

1.  **Our self-signed (non-malicious cert).**  It's cruel and irresponsible to call this "malicious" as it's a cert only generated for this one PC.  This project is open source, you can audit our process for generating and installing this cert.  There's nothing malicious about it, it's required for secure communication between a webpage running HTTPS and our software.  This cert is removed when the software is uninstalled.
2. **The Chrome policy to make this trusted.**. This is persistent because we have no way of knowing if this policy was use by another application.
   > ```bash
   > defaults read /Library/Preferences/org.mozilla.firefox
   > ```
   If you're knowledgeable enough to know how to pull this policy from the system configuration, you're likely smart knowledgeable enough to disable it.  Firefox is the only browser that doesn't trust system-wide certificates by default.  Our old strategy was to only modify the Firefox certificate store, but that process changed over time and was very difficult to maintain.

If you think our documentation needs to be improved in this area, just let us know where.  We're receptive to ideas, but we really don't like finger pointing.
