### ISSUE TITLE
PDFCreator + Landscape

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#196]
I have not been able to reproduce this with other printers (PDFwriter for Mac, Microsoft Print to PDF) than PDFCreator, but since this is what we use for baseline testing, I thought it was worth writing.

Note: I've used PDF printing as an example, but this is observed using HTML, PDF, and Image printing.

As of 2.0.4-RC.1, when printing landscape using PDFCreator (Windows), the file is changed (when using Letter) to 11x8.5in as opposed to the image being "rotated" and the page size remaining 8.5x11in.

![image](https://cloud.githubusercontent.com/assets/12505463/25978222/0259d2be-368f-11e7-8622-a236e32f6783.png)

When tested against 2.0.3 stable and this behavior is different.

![image](https://cloud.githubusercontent.com/assets/12505463/25978202/e058adfc-368e-11e7-89f4-80ec384c5ccc.png)

**Comment by tresf** [comment]
@klabarge sorry, this is a feature.  Somewhat explained here:  https://github.com/qzind/tray/commit/e8d48217d497157d42e2e99c513b283d38630ce3, https://github.com/qzind/tray/commit/76abb698faa7ae382ebda60c735afc2386e5b6fb

Somewhat hinted here https://github.com/qzind/tray/issues/158#issue-203290534

> The PDF printed with Acrobat, when printed to PDFCreator, creates a 11.0 x 8.5 PDF

I believe most of this happened in a private conversation with Brett and skipped the tracker.

**Comment by tresf** [comment]
... on second thought.... maybe this is a bug.  So the printer driver sees the content exactly 90 degrees of what would be a perfect fit and spins it on us.  That certainly sounds like a bug, but it may actually be a bug with the printer driver.

@lite1979 can you test on a physical printer and post your output?

**Comment by lite1979** [comment]
Something is definitely fishy here. Portrait (default) PDF printed perfectly on my Brother HL-L2380DW, but landscape PDF resulted in a blank page...

![screenshot 7](https://cloud.githubusercontent.com/assets/3408749/26003049/99193ae4-36ff-11e7-9c29-1589c7856b60.png)

**Comment by bberenz** [comment]
It looks like this is just how it reports a rotated page:

![same](https://cloud.githubusercontent.com/assets/5912715/26007769/f1049838-370f-11e7-8cf2-b62672c1262c.png)

This is the same document/settings printed with two different drivers. And after e8d48217d497157d42e2e99c513b283d38630ce3 we are expecting most pdf drivers to preview how pdfcreator does.
We don't flip dimensions anywhere either, we just tell the print driver we want landscape. So if this is a bug, it would be in the driver, not qz.
Have you tried viewing the document in a different pdf viewer and seeing what it reports about the page?

@lite1979, can you post the full logs from the failed print?

**Comment by lite1979** [comment]
Not sure if this is long enough to constitute a gist or pastebin, but here you are:

[DEBUG] 2017-05-12 15:49:38,880 @ qz.printer.PrintServiceMatcher:?
        Searching for PrintService matching bro
[DEBUG] 2017-05-12 15:49:38,936 @ qz.printer.PrintServiceMatcher:?
        Found 9 printers
[DEBUG] 2017-05-12 15:49:38,937 @ qz.printer.PrintServiceMatcher:?
        Found match: Brother HL-L2380DW series Printer
[DEBUG] 2017-05-12 15:49:47,685 @ qz.ws.PrintSocketClient:?
        Message: {"call":"print","promise":{},"params":{"printer":{"name":"Brother HL-L2380DW series Printer"},"options":{"colorType":"color","copies":"1","density":"","duplex":false,"fallbackDensity":null,"interpolation":"","jobName":"","margins":"0","orientation":"landscape","paperThickness":"","printerTray":"","rasterize":true,"rotation":"0","scaleContent":true,"size":null,"units":"in","altPrinting":false,"encoding":"","endOfDoc":"","perSpool":"1"},"data":[{"type":"pdf","data":"file:///C:/Program%20Files/QZ%20Tray/demo/assets/pdf_sample.pdf"}]},"timestamp":1494618587679,"uid":"o42rmq"}
[WARN] 2017-05-12 15:49:47,697 @ qz.ws.PrintSocketClient:?
        Bad signature on request
[INFO] 2017-05-12 15:49:49,139 @ qz.common.TrayManager:?
        Allowed localhost to print to Brother HL-L2380DW series Printer
[DEBUG] 2017-05-12 15:49:49,328 @ qz.utils.PrintingUtilities:?
        Allowing 1 simultaneous processors based on memory available (518 MB)
[TRACE] 2017-05-12 15:49:49,329 @ qz.utils.PrintingUtilities:?
        Waiting for processor, 0/1 already in use
[DEBUG] 2017-05-12 15:49:49,354 @ qz.utils.PrintingUtilities:?
        Using qz.printer.action.PrintPDF to print
[DEBUG] 2017-05-12 15:49:49,357 @ qz.printer.PrintServiceMatcher:?
        Searching for PrintService matching Brother HL-L2380DW series Printer
[DEBUG] 2017-05-12 15:49:49,360 @ qz.printer.PrintServiceMatcher:?
        Found 9 printers
[DEBUG] 2017-05-12 15:49:49,361 @ qz.printer.PrintServiceMatcher:?
        Found match: Brother HL-L2380DW series Printer
[WARN] 2017-05-12 15:49:49,375 @ qz.printer.PrintOptions:?
        Cannot read  as a double for density, using default
[WARN] 2017-05-12 15:49:49,376 @ qz.printer.PrintOptions:?
        Cannot read  as a valid value for interpolation, using default
[WARN] 2017-05-12 15:49:49,379 @ qz.printer.PrintOptions:?
        Cannot read  as a double for paperThickness, using default
[DEBUG] 2017-05-12 15:49:50,146 @ qz.utils.PrintingUtilities:?
        Found Resolution: null
[WARN] 2017-05-12 15:49:50,147 @ qz.printer.PrintOptions:?
        Cannot read null as a double for fallbackDensity, using default
[DEBUG] 2017-05-12 15:49:50,610 @ qz.printer.action.PrintPDF:?
        Parsed 1 files for printing
[TRACE] 2017-05-12 15:49:50,879 @ qz.printer.action.PrintPixel:?
        DPI: 600.0      CNV: 72.0
[TRACE] 2017-05-12 15:49:50,880 @ qz.printer.action.PrintPixel:?
        Drawable area: 0.0,0.0:11.0,8.5
[TRACE] 2017-05-12 15:49:50,882 @ qz.printer.action.PrintPixel:?
        [landscape, color, (0.0,0.0)->(279.4,215.9)mm, 60000x60000 dphi]
[INFO] 2017-05-12 15:49:50,901 @ qz.printer.action.PrintPixel:?
        Starting printing (1 copies)
[WARN] 2017-05-12 15:49:50,903 @ qz.printer.action.PrintPixel:?
        Supported printer densities not found
[TRACE] 2017-05-12 15:49:51,440 @ qz.printer.BookBundle:?
        Requested page 0 for printing
[DEBUG] 2017-05-12 15:49:51,440 @ qz.printer.PDFWrapper:?
        Paper area: 0,0:792,612
[TRACE] 2017-05-12 15:49:54,095 @ qz.printer.BookBundle:?
        Requested page 0 for printing
[DEBUG] 2017-05-12 15:49:54,096 @ qz.printer.PDFWrapper:?
        Paper area: 0,0:792,612
[TRACE] 2017-05-12 15:49:55,699 @ qz.printer.BookBundle:?
        Requested page 0 for printing
[DEBUG] 2017-05-12 15:49:55,700 @ qz.printer.PDFWrapper:?
        Paper area: 0,0:792,612
[TRACE] 2017-05-12 15:49:56,165 @ qz.utils.PrintingUtilities:?
        Returning processor back to pool
[ERROR] 2017-05-12 15:49:56,222 @ qz.ws.PrintSocketClient:?
        Connection error
java.lang.RuntimeException: Cannot call method public void qz.ws.PrintSocketClient#onMessage(org.eclipse.jetty.websocket.api.Session, java.io.Reader) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, org.eclipse.jetty.websocket.common.message.MessageReader]
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.unwrapRuntimeException(CallableMethod.java:93)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:75)
        at org.eclipse.jetty.websocket.common.events.annotated.OptionalSessionCallableMethod.call(OptionalSessionCallableMethod.java:68)
        at org.eclipse.jetty.websocket.common.events.JettyAnnotatedEventDriver$2.run(JettyAnnotatedEventDriver.java:210)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.awt.image.DataBufferInt.<init>(Unknown Source)
        at java.awt.image.Raster.createPackedRaster(Unknown Source)
        at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
        at java.awt.image.BufferedImage.<init>(Unknown Source)
        at org.apache.pdfbox.printing.PDFPrintable.print(PDFPrintable.java:175)
        at qz.printer.PDFWrapper.print(Unknown Source)
        at qz.printer.BookBundle.print(Unknown Source)
        at sun.awt.windows.WPathGraphics.redrawRegion(Unknown Source)
        at sun.print.RasterPrinterJob.printPage(Unknown Source)
        at sun.print.RasterPrinterJob.print(Unknown Source)
        at qz.printer.action.PrintPixel.printCopies(Unknown Source)
        at qz.printer.action.PrintPDF.print(Unknown Source)
        at qz.utils.PrintingUtilities.processPrintRequest(Unknown Source)
        at qz.ws.PrintSocketClient.processMessage(Unknown Source)
        at qz.ws.PrintSocketClient.onMessage(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jetty.websocket.common.events.annotated.CallableMethod.call(CallableMethod.java:70)
        ... 5 more

**Comment by lite1979** [comment]
Removing 32-bit Java from the machine and installing 64-bit Java from the off-line installer has given me a successful landscape PDF print.

**Comment by klabarge** [comment]
I tested `landscape` printing to a physical printer. It appears that 2.0.4-RC.1 prints landscape in reverse.


![image](https://cloud.githubusercontent.com/assets/12505463/26118640/a8b3eef4-3a38-11e7-89a3-ffa9bb460b13.png)

**Comment by tresf** [comment]
@klabarge, thanks.  Reminds me somewhat of this unanswered question: http://stackoverflow.com/questions/42478745/is-landscape-90-or-270-degrees

Does REVERSE LANDSCAPE and non-PDF content (images, HTML) behave the same now?

@bberenz can confirm but the major difference is we're setting a property in the document that helps the driver understand text direction and that seems to be having some interesting results between various print drivers.

If this is desired behavior we may best keeping it, but it could cause grief for customers that expect portrait content to turn and print at the same end of the paper.

If this is undesired, we may be better off shelving this fix for a major release (e.g. 2.1).

**Comment by bberenz** [comment]
> the major difference is ...

The only changes to PDF printing from the 2.0.3 release currently appear to be 76abb698faa7ae382ebda60c735afc2386e5b6fb (text direction) and 61a2f1b9757c6aa8bc2725c645f86c0a43f163bf ('auto' rotation). Auto rotation shouldn't have an effect on the page if you are explicitly setting the orientation though.

> .. we're setting a property in the document that helps the driver understand text direction ...

Not exactly a property though, we are just drawing a space-character on the actual document. PDFCreator (and some other drivers) seems to then pick up on the text orientation and print it with a rotated page size.

**Comment by tresf** [comment]
> PDFCreator (and some other drivers) seems to then pick up on the text orientation and print it with a rotated page size.

@bberenz is there a chance we simply need to adjust the way we draw this space character to match orientation?

**Comment by bberenz** [comment]
> is there a chance we simply need to adjust the way we draw this space character to match orientation?

We don't have that level of control. We are given a `Graphics` object, call [`drawString`](https://docs.oracle.com/javase/8/docs/api/java/awt/Graphics.html#drawString-java.lang.String-int-int-) on it, and then pass the graphics over to PDFBox to draw. The resulting orientation is handled at a higher level by the print libraries.

> I tested landscape printing to a physical printer. It appears that 2.0.4-RC.1 prints landscape in reverse.

So I tested a few versions back, because I initially had 2.0.2 installed on my machine and had different results than you. We aren't very consistent in direction:
![compare](https://user-images.githubusercontent.com/5912715/27499689-f2f1d0c2-5832-11e7-8db7-f4ad1f6a53ff.png)
v2.0.0 also appears to match 2.0.1 and 2.0.3, but the content is cut off due to an old pdfbox bug so I omitted it here.

This is how we are setting orientation across versions:

| version | orientation |
| --- | --- |
| 2.0.1 | Degrees - Land: 270, Reverse: 90 |
| 2.0.2 | Degrees - Land: 90 Reverse: 270 |
| 2.0.3 | Degrees - Land: 270 Reverse: 90 |
| 2.0.4 | PageFormat class constants |

The way we orient the page in 2.0.4 changed when we applied the text direction changes. I should have caught that in my previous comment, but that appears to be how the orientation changed sides.

> Does REVERSE LANDSCAPE and non-PDF content (images, HTML) behave the same now?

Actually, LANDSCAPE seems to now be consistent with the way images/html are orientated, so I think that's a strong case that 2.0.3 pdf's were wrong instead:
![compare_type](https://user-images.githubusercontent.com/5912715/27499975-401da6c2-5834-11e7-8644-929eade16694.png)

**Comment by tresf** [comment]
Thanks @bberenz.  I'll defer to @klabarge.  It seems like we still have a bug with Mac though.  https://github.com/qzind/tray/issues/196#issuecomment-301850727.  What's interesting is the native MacOS print dialog doesn't have "reverse landscape" however it does have an option to [rever page orientation and an option to flip the content horizontally](https://user-images.githubusercontent.com/6345473/27513418-25221772-5933-11e7-9133-9fe5bba09f1b.png).

**Comment by klabarge** [comment]
`landscape` is broken on macOS in the pdf-fix branch. Tracking in a separate issue: https://github.com/qzind/tray/issues/197#issuecomment-317566649

to quote the latest comment:

> I reproduced two issues on macOS:
>1. `landscape` and `reverse-landscape` are the same on macOS.
>1. `landscape` on macOS is printed the same as `reverse-landscape` on Windows and Linux. It is oriented opposite of these platforms.

**Comment by tresf** [comment]
@klabarge are we closing this as `wontfix` then?

**Comment by klabarge** [comment]
@tresf yes, the original post is `wontfix`
