### ISSUE TITLE
Version number wrong in 2.0.4

### ISSUE THREAD

**Issue by bigware** [qzind/tray#206]
In file qz-tray.js, the version is still 2.0.3-2. Is there a reason for that? Since 2.0.3, I've been using the function qz.api.getVersion() to match with qz.version so I alert a specific computer if they didnt update to the latest version yet. Will you not be updating this file each time with a new version number?

**Comment by tresf** [comment]
>  Is there a reason for that?

The `qz-tray.js` version won't necessarily match exactly to the `qz-tray.jar` version and this is because we don't always modify the API when a new release is offered.

In this case, you are right.  We had modified `qz-tray.js` but failed to bump the internal version, so closed via https://github.com/qzind/tray/commit/fc917880ed215a8dd1f8b1ba5525de703c1b1377.  Also updated in `npm`.

> I alert a specific computer if they didnt update to the latest version yet

There's no way to do this currently.  You could look at https://api.github.com/repos/qzind/tray/releases and search for `"name": "2.0.4",` so as long as `"prerelease": false,` but you may also want to put a check in there not to warn when `2.1` is released.
