### ISSUE TITLE
Font sizes and currnecy symbols

### ISSUE THREAD

**Issue by ganesanasandeep** [qzind/tray#216]
We are building a POS software, we need to print currency symbol on receipt.
I have googled for that and couldn't find a solution. I have tried with ascii hex value but that didn't work with me.

How can I increase font size to certain px, which was not present in [https://qz.io/wiki/2.0-raw-printing#escpos](url). We are using raw method.

**Comment by lite1979** [comment]
We offer examples for ESC/POS as a courtesy, but we are not the authors of this printer language.  Closing this issue as it is not a problem with QZ-Tray.  Please read further for more information regarding your problem:

Pixel-based fonts are only supported by certain printers and firmware versions, which will depend on your hardware, not our software.  Please refer to the ESC/POS manual that corresponds to your printer to see if this can be achieved. In my experience, px-sized fonts are usually only used by LX-type dot-matrix printers, not by thermal receipt printers. The LX-type dot matrix printers often use ESC/P2, which is slightly different from ESC/POS.  Thermal receipt printers typically have a font 'A' (smaller) and font 'B' (larger) by default. You may be able to choose alternate fonts based on the firmware of the printer. 

Regarding your currency symbol, many of the ESC/POS manuals offer a list of code pages near the end of the literature.  These can be Eastern European, Western European, Vietnamese and so forth.  Once you have switched the printer to use the new codepage, you should be able to print your currency symbol.

Note:  Some printers require special firmware from the manufacturer in order to print certain languages/fonts.  These printers must be ordered with this firmware in order to properly print those languages/fonts.  Here is a conversation describing this limitation:

https://www.experts-exchange.com/questions/22804647/Print-Arabic-characters-to-Epson-TM-T88-compatible-Receipt-Printer.html

Again, I am closing this issue as not our bug, but please feel free to contact me directly at lite@qz.io if you need any help with your code. :)
