### ISSUE TITLE
Problem on build.xml:219 

### ISSUE THREAD

**Issue by guncebektas** [qzind/tray#232]
When i run `ant nsis -Dauthcert.use=cert/cert.pem` on mac, i'm getting this error

> ....qztray/build.xml:219: Execute failed: java.io.IOException: Cannot run program "makensis" (in directory "....qztray"): error=2, No such file or directory

What could be the solution.

build.xml:219 is
```
<exec executable="${nsisbin}" failonerror="true" >
    <arg value="${windows.launcher.out}"/>
</exec>
```

**Comment by tresf** [comment]
The installer will look for `makensis` in either `%ProgramFiles%/NSIS/makensis.exe` on 32-bit or `%ProgramFiles(x86)%/makensis.exe` on 64-bit per [build.xml#L236-L244](https://github.com/qzind/tray/blob/2.0/build.xml#L236-L244).

If something has changed and `makensis.exe` is in a different location, we will need to be made aware so that we can update our packager.

**Comment by guncebektas** [comment]
so it's not possible to compile for windows on mac. Am i right?

**Comment by tresf** [comment]
> so it's not possible to compile for windows on mac. Am i right?

For mac, just `brew install nsis`.

**Comment by tresf** [comment]
@guncebektas looks like  we had the `nsis` and `makeself` identified in our Linux dependencies but never added them to our Mac dependencies.  Added https://qz.io/wiki/install-dependencies#mac.

**Comment by guncebektas** [comment]
thank you very much
