### ISSUE TITLE
Would it be possible to make a chrome extension that be run in background that will make the printer print?

### ISSUE THREAD

**Issue by welrachid** [qzind/tray#239]
Hi guys.
Not sure how to ask a question without making it an issue, but i thought i would ask in forum so that everyone could "learn" from it.

Im just curious if it would be possible to make a chrome extension that would be able to be notified from our server that there is a "document" ready to be printed? even though the browser is shut down (using chrome's ability to have services running after close)

Thanks

**Comment by tresf** [comment]
It seems possible  https://developers.google.com/web/fundamentals/push-notifications/
It's out of the scope of our current product since we don't yet offer a Chrome plugin version of our software, but it appears that part of the `Notification` can register a worker that can fetch these from the server even when the browser is not running.

https://hacks.mozilla.org/2016/01/web-push-arrives-in-firefox-44/

On the other hand, QZ Tray could (theoretically) be enhanced to subscribe to a remote URL and have it's own notification system as well, but it would run outside of the browser (since QZ Tray uses Java outside of the browser) and then offer to fire up the default browser... which may still be out of scope and likely not an experience a web developer would be looking for.

**Comment by welrachid** [comment]
That would be awesome, since this would make it possible for us not to have the browser open when we make auto-prints.
Maybe i should look into this. Doing a chrome plugin is relatively simple

**Comment by tresf** [comment]
@welrachid since we already offer a print-server mode, there are some other ways this could be done, such as sending the print job through HTTP directly to the PC that's already running QZ Tray.

This is out of scope for our project but please feel free to offer research here.  If it is something we find value in adding to our base product, we'd be happy to reopen the issue.
