### ISSUE TITLE
Signing breaks when using 1.4960600000000001 for height, width, or marigns

### ISSUE THREAD

**Issue by tresf** [qzind/tray#30]
Probably an assumption of rounding, but seems like something we may be able to tackle client-side.

This number is a result of `38 mm` * `0.039370` to convert to inches (about 1.5 inches)

Since 1.5 inch labels are fairly common among Dymo printers, this is worth investigating and possibly documenting.

**Comment by bberenz** [comment]
>[DEBUG] 2016-04-12 16:52:41,123 @ qz.ws.PrintSocketClient:166
>	Message: {"call":"print","promise":{},"params":{"printer":{"name":"PDFCreator"},"options":{*[DEFAULTS OMITTED]*,"size":{**"width":1.4960600000000002,"height":0.7480300000000001**},"units":"in"},"data":[{"data":"http://localhost:8080/images/logo.png","type":"image","format":"file"}]},"signature":"mObMcgebzts8*[...snip...]*/KlYhK7EgeNnuUfTutfgG+w==","timestamp":1460494361104,"uid":"ru56d9"}
>[TRACE] 2016-04-12 16:52:41,124 @ qz.ws.PrintSocketClient:208
>	**Valid signature from Sellers Toolbox**

I'm actually not able to reproduce this with our certificate. Can you post the config you are using and the message qz is receiving? And also, what language are you using to sign the message?

**Comment by cruzzan** [comment]
Browser: I have tried it on IE, Edge, Chrome, Firefox and it sees to affect IE and Edge
OS: I have only tried it on Windows 7 and Windows 10
Version of QZ: I have tried RC3 (With that i get the approval dialog, that i need to manually approve the request), RC4 (Here the request just gets rejected), 2.0 alpha 6 (Same result as RC3), RC5 patch 2 (Same result as RC3).
Language: We are using PHP to sign the message with the openssl_sign function.
Message as outputed to the log (Minus the data portion as it is a massive b64 string): "call":"print","promise":{},"params":{"printer":{"name":"CutePDF Writer"},"options":{"colorType":"color","copies":1,"density":0,"duplex":false,"interpolation":"bicubic","jobName":"WebDocPrintout","margins":0,"orientation":null,"paperThickness":null,"printerTray":null,"rasterize":true,"rotation":0,"scaleContent":true,"size":{"height":1.4960600000000001,"width":3.97637},"units":"in","altPrinting":false,"encoding":null,"endOfDoc":null,"perSpool":1}

As far as i have been able to tell this is probably connected to how i sign, and my actual cert and key that i sign with. If that is the case i will be more then happy to send over more info and things like that, but not openly since this cert and key is in our production at the moment.

**Comment by bberenz** [comment]
@cruzzan Thanks for the details, looks like this is an issue with how IE handles floating point numbers rather than anything with signing.

@tresf As far as I can tell, the best way to fix this internally is to force any dimensions as strings before signing it, or forcing numbers through `toFixed` to round tailing values like this. Though this could complicate any pre-signing methods in place. Thoughts?

**Comment by tresf** [comment]
We won't be fixing this as it's a browser compat problem.  If you need to use `1.4960600000000002`, either send it as a string or use `toFixed(...)` and it will validate just fine.

By the time we get this in IE, it's too late (it's already been changed).  QZ changes it too, but consistently with Firefox, Chrome, Safari so it's benign on those browsers.

If we see `1.4960600000000002` in the logs, we'll know why signing breaks.  Thanks for the details.
