### ISSUE TITLE
Updated to 2.0.6 and stop working

### ISSUE THREAD

**Issue by giolazzareschi** [qzind/tray#300]
Hi,

I've been using version 2.0.3 on my machine then I updated to 2.0.6 and Qz Tray stop working. When I access https://localhost:8181/ it just responds "Address can not be reached" and nothing can be printed.

I did just updated only. Just donwloaded the new version and did "next > next > finish". Also I tryied to create manually a new certificate (trying to find a solution) and this showed to console:

![capturar](https://user-images.githubusercontent.com/4623190/38386613-8cfaae0c-38eb-11e8-916a-6b005295f8cf.JPG)

"[FAILED] creating and SSL CSR"

My java -version:

Picked up _JAVA_OPTIONS: -Xmx512M
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)

I notice when I try install 2.0.6 version I keeps a little time more than usual on "creating SSL certificate" step.

When I downgrade to 2.0.3 everything works fine.

I'm using windows 10 64 bits, and my firewalls are all disabled.

Can I give any differente information? Or do something to find an solution?

**Comment by tresf** [comment]
> I notice when I try install 2.0.6 version I keeps a little time more than usual on "creating SSL certificate" step.

This is due to the stricter Firefox requirements for self-sogned certificates.  This observation is correct, it's the additional overhead of a two-step cert process, new to 2.0.4.

> "[FAILED] creating an SSL CSR"

We've never seen this before.  We'd first recommend reinstalling latest Java 8 from offline and re-running the installer.  If that doesn't help, we'll have to add some debug steps to `windows-keygen.js` to find out what's going wrong.

More information on what caused this keygen change is available here:

https://stackoverflow.com/q/44550970/3196753


Note, we fully tested 2.0.6 on all major platforms and browsers before release and have several clients running it in production for weeks so our initial troubleshooting is going to be around your specific environment.

**Comment by giolazzareschi** [comment]
Ok! I'm going to reinstall my java and will feedback further. Thanks for the fast reply.

**Comment by giolazzareschi** [comment]
Yep it worked.

I just updated my java version and back to normal.

I'll leave here for documentation purposes.

OLDER JAVA VERSION:
Picked up _JAVA_OPTIONS: -Xmx512M
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) Client VM (build 25.111-b14, mixed mode)


NEW JAVA VERSION:
C:\WINDOWS\system32>java -version
Picked up _JAVA_OPTIONS: -Xmx512M
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) Client VM (build 25.161-b12, mixed mode, sharing)

Also the SSL certificate for overriding the "localhost" default server worked too.

![image](https://user-images.githubusercontent.com/4623190/38387945-0d52c590-38f0-11e8-9e1d-06e8aceeeebc.png)


Thanks a lot.
