### ISSUE TITLE
Scrollbar in HTML when using rasterize

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#31]
There's a scrollbar that appears on the right side of prints when using HTML and `rasterize` and effects Windows, OS X, and Linux.

* This screenshot is from Windows, but it is very similar (if not the same) to OS X and *some* of Ubuntu's results:

 ![image](https://cloud.githubusercontent.com/assets/12505463/14445758/d1f4aaac-001d-11e6-9380-843b90fdf76e.png)

**Ubuntu has different results:**

* This is the size of the image that is printed by default.  Notice in the top right hand corner there's a gray "bar".  If you zoom in on this, you can see it is a scroll bar.

  ![image](https://cloud.githubusercontent.com/assets/12505463/14444910/df9ddcb6-0016-11e6-80a9-b64e569554d3.png)

* Sometimes the printout looks like the [first image](https://cloud.githubusercontent.com/assets/12505463/14445758/d1f4aaac-001d-11e6-9380-843b90fdf76e.png). This seems to happen when setting a custom page size.

* Sometimes the scrollbar appears like this (I'm not sure what triggers it yet):

 ![image](https://cloud.githubusercontent.com/assets/12505463/14445037/e03a0da6-0017-11e6-971d-bad462e9c2db.png)

**Comment by klabarge** [comment]
Per issue [#32](https://github.com/qzind/tray/issues/32) this also happens (sometimes) when `rasterize: false` on Ubuntu.

**Comment by bberenz** [comment]
Per ddbcd0e115230bff9641085d6eed46d58ce82e5c, web captures force the removal of scrollbars from the document. Instead clipping any portion of the page that falls outside the capture.

Since there is already code to try and resize the page to the scroll height, it shouldn't affect captures greatly. This seemed to really just affect the prints that tried to zoom in on the capture, and in most cases you can see the scrollbar has just a small fraction available to move anyways. 
Well except ubuntu, but there seems to be a separate issue around that one.

**Comment by klabarge** [comment]
Tested on Windows, OS X, and Ubuntu - no scroll bars :+1:
