### ISSUE TITLE
Restart QZ Tray after cert override/regen

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#323]
QZ Tray must be restarted on Windows and macOS whenever the cert  scripts are used for overriding or regenerating a certificate. Linux requires the certificate regeneration/override to happen at install time, so is unaffected. 

We should automatically restart QZ Tray in these scripts. It's one less step administrators will have to deal with.

* [ ] Windows: [windows-keygen.js](https://github.com/qzind/tray/blob/2.0/ant/windows/windows-keygen.js.in)
* [ ] macOS: [apple-keygen.sh](https://github.com/qzind/tray/blob/2.0/ant/apple/apple-keygen.sh.in)

**Comment by tresf** [comment]
I think we can safely move the process killing logic from the installer scripts to the certificate generation scripts to tackle this problem.  I'm not sure if this is warranted on the 2.0 branch or if it should be bumped to the 2.1 branch.  Help appreciated on this one @klabarge.

**Comment by tresf** [comment]
I've added the code to shutdown QZ Tray.  This will be default as part of 2.0.8.

Restarting QZ Tray has not been added.  I believe this is best handled by enhancing the internal WebSocket listener and sending a restart message to the websocket itself.  Due to the amount of refactoring involved, this is better slated for 2.1 branch.
