### ISSUE TITLE
Printer tray selection for PDFs

### ISSUE THREAD

**Issue by tresf** [qzind/tray#326]
PDF printing seems to ignore the printer tray selection in QZ Tray 2.1.

1. Install Boca Windows driver from http://www.bocasystems.com/bocaprinterdrivers.zip
2. Add a new `FILE:` printer that utilizes the `Boca FGL 26/46 200 DPI` driver.
3. Using `sample.html`, print a PDF

Now, repeat the above steps, but provide the tray name `P1 - Rotate 180` tray.

Compare the results.

If selected properly, the FGL output should reflect the rotation (`<RTE>`) command:

```diff
- <P1><PM><RE0><DI><p>
+ <P1><RTE><PM><RE0><DI><p>
```

2.1 does not properly select this tray for output when printing PDFs

**Comment by lite1979** [comment]
Behavior is the same for "Print Image" as "Print PDF" using the Boca driver and "P1 - Rotate 180"

The print job does not get rotated to the other physical limit of the printable area.

HTML, on the other hand, uses the "P1 - Rotate 180" and performs as expected - the print job gets rotated to the other physical limit of the printable area.

**Comment by bberenz** [comment]
Testing on the multi-tray printer provided by @tresf, I am able to get PDFs to print on different trays.  
Though that particular printer uses "Paper Cassette" instead of "Tray", so I've updated the code under 3562d7fc7e0e52c5f2d935932445c014409ebf05 to look for both designations. This only affects using a numeric value for the printerTray option though. Using the full string name even before the code change allowed the PDF to select which tray it prints from successfully.

My local testing using the boca driver also appears to append the expected `<RTE>` value when providing the named tray value "P1 - Rotate 180". Can you provide logs of your failed test cases?

**Comment by tresf** [comment]
@lite1979 can you please retest on the latest 2.1 branch and provide a link to the debug logs in gist format to @bberenz?

**Comment by tresf** [comment]
Per @lite1979's comments in #61, this is working.  Closing.
