### ISSUE TITLE
Abstract Printer RAW to XML

### ISSUE THREAD

**Issue by blaggacao** [qzind/tray#341]
Just wanted to share this excellent xml2escpos preprocessor library https://github.com/miracle2k/py-xml-escpos which in it's original form  https://github.com/fvdsn/py-xml-escpos is incorporated into Odoo.

It would be interesting to see, if @miracle2k would be willing to expand the scope to support other vendor languages or if qz would be willing to think of incorporating such preprocessing functionality within qz, which would definitely be a big value added to present a common interface for label printing jobs...

**Comment by tresf** [comment]
This is a cool project, but we don't have any intentions on writing a markup language around a proprietary language.  We think the industry is more likely to switch to ESCPOS-less printing, which 2.1+ can do pretty well with HTML and 2.0+ can do with PDF.

There are a few problems with the above proposal...

1. The major on I've seen is that nearly all programming manuals I've seen make claim that they're proprietary so re-inventing them in a higher language can be frowned upon.
2. Many of these low-level languages have an API that can be used for layout and functionality and would be well suited for #63.  They're not a one-size-fits-all solution, but they provide the libs to talk natively without re-writing what the vendor engineers have already done.
3. Harder to troubleshoot and support since it'll be one more additional step in the Rube-Goldberg process of printing.
4. For label-printing specifically, there are already services which offer this such as labelary and koditPaperFlex.  koditPaperFlex is a client of ours, so we try to let them be the ZPL experts while we be the plugin that sends it.
5. We're adding new languages fairly often, so the user experience will be fragmented until we R&D around each printer.
6. The commands are often hardware dependent and firmware version dependant causing mixed results and compat issues.

Just one example is magnetic card printing... we'd have to write a DOM node to handle magnetic encoding, but magnetic cards can do ISO formatted or raw formatted magnetic strips.  We'd end up spending more time writing meta languages than we would writing our own code and I think that would be an injustice to our clients.

That said, if someone wants to spearhead the equivalent of PostScript -- but for industry printers -- and they think it's possible without driver intervention, we'd happily place it into our build system, but we'd need the project to be well maintained and -- if possible -- ofer a commercial support option so that we can warranty it to our clients. :)

**Comment by tresf** [comment]
> we don't have any intentions on writing a markup language around a proprietary language

Closing as per our stated intents.  Feel free to request a reopen if someone begins work on this.
