### ISSUE TITLE
Remember this decision not obvious in Ubuntu 18.04

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#426]
The "Remember this decision" option in the Trusted certificate dialogue is not obvious in Ubuntu 18.04

**Java:** openjdk version "11.0.1" 2018-10-16
**Tray:** 2.0.9-RC4

**Unchecked**
![image](https://user-images.githubusercontent.com/12505463/53616378-41754c80-3bb0-11e9-8061-88a38d3b71c6.png)

**Checked**
![image](https://user-images.githubusercontent.com/12505463/53616406-58b43a00-3bb0-11e9-805b-fd8047501424.png)

**Comment by tresf** [comment]
Appears to be a bug with Gnome3 and Java.  Fixed in Java 13, I wonder if we'll see a backport?
https://bugs.openjdk.java.net/browse/JDK-8203627

**Comment by tresf** [comment]
@klabarge looks like this was backported to 11 on February 14th, slated for 11.0.4 release.
* https://bugs.openjdk.java.net/browse/JDK-8221108
* https://bugs.openjdk.java.net/browse/JDK-8219188

At time of typing this, AdoptOpenJDK is on 11.0.2 and working to push to 11.0.3.  I'll close this since there's an eventual fix in the pipeline.  How soon that becomes available, I'm not sure, but since it's resolved upstream, closing.
