### ISSUE TITLE
About page port detection

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#449]
I was recently assisting a client where QZ Tray was launching on incorrect ports, which exposed a discrepancy with the ports listed in the About page and the actual ports QZ Tray was using.

![image](https://user-images.githubusercontent.com/12505463/58099060-e3517780-7ba8-11e9-8607-2697a9389043.png)

In this example, QZ Tray launched on port `22997`, However he HTTP About page was returning ports `8181` and `8182` as the ports in use.

![image](https://user-images.githubusercontent.com/12505463/58099174-214e9b80-7ba9-11e9-84e5-4580ef0fa12c.png)

**Comment by tresf** [comment]
Reviewing the code, this is because `TrayManager` loops over the actually-used ports by the Jetty server and blindly lists them whereas the About Page uses the port index to display what they *should* be.  In the case of the OP, the port reassignment is one of QZ Tray's great mysteries.  After reviewing the code used for the About dialog, I think it's OK for now, since 99.9% of the time it's correct, but I'll see what @bberenz has to say.

**Comment by bberenz** [comment]
Well the reassignment is definitely external, all qz knows is its list of usable ports (what the about page pulls from). We could probably have the about page pull from the same source the manager does for that log, but this seems like unsupported/unwanted behavior so I'm not sure it has much advantage to doing so.

**Comment by tresf** [comment]
> so I'm not sure it has much advantage to doing so.

I'm fine with this answer.
