### ISSUE TITLE
Too many active job

### ISSUE THREAD

**Issue by sauravgaursmith** [qzind/tray#475]
Hi Guys, I'm facing an error which states that "Too Many Active Jobs" on only a specific machine. Is it due to a number of pending request ? How can I get rid of it ?
See screenshot: 
![imageedit_5_6430009488](https://user-images.githubusercontent.com/25001992/62369147-5170ce00-b54c-11e9-94f1-92c4b10eb7d4.png)

**Comment by sauravgaursmith** [comment]
Hi Guys... 
Please, any one there to help me out ?

**Comment by tresf** [comment]
@sauravgaursmith it sounds like something on this system is queuing requests.  This could be natural (a system under heavy load), or unnatural (a misconfigured print queue).

CUPS does provide ways to override this using the `cupsd.conf` file.
https://askubuntu.com/a/1102118/412004

Specifically, the stack overflow article claims the following should help
```js
MaxJobs 1000
MaxJobsPerUser 500
MaxJobsPerPrinter 500
MaxJobsPerClient 500
```

Can you provide more information about how this problem occurs?  For example, are you sending many separate print jobs in a row?  You may be able to consolidate some of these into a single job, but we'd need to know more about what type of data is being sent.

For example, we have some spool control which allows you to send multiple jobs in one file and then split them up based on delimiters.

https://qz.io/wiki/2.0-Raw-Printing#advanced-print-spooling

... so for EPL, `P1\n` or ZPL `^XZ\n` and then spool every 5, 10 or 20 jobs instead of every 1.

**Comment by sauravgaursmith** [comment]
Thanks Tres Finocchairo...
Yes, it was due to a lot of print jobs in queue.

**Comment by tresf** [comment]
EPL, ZPL, ESCPOS or other?  Is there a chance we can correct this by combining print requests?  Can you offer any other information?

**Comment by sauravgaursmith** [comment]
Hi @tresf 
We are using ZPL. We send request with the no of prints and printer script. For now, we have cleared pending request in the queue. There were more than 10K request in queue.

**Comment by tresf** [comment]
> There were more than 10K request in queue.

Ok, thanks, but I'm not sure how that's a QZ problem.  Can you help explain how that is a QZ problem?  If something is wrong with the queue, QZ can't fix it.

**Comment by sauravgaursmith** [comment]
Yeah, actually this is related to system. I was just seeking help if
anybody have faced the same problem.

**Comment by tresf** [comment]
Thanks for clarification.  We'll close this out on our end then.
