### ISSUE TITLE
serial communication Baud Rate 2400 not supported

### ISSUE THREAD

**Issue by furqan56** [qzind/tray#476]
for some reason baud rate 2400 is not in the valid baud rate list whenever we send 2400 it set it to default 9600 I have seen in the code it's, not in the valid list SerialUtilities.java

**Comment by tresf** [comment]
Appears to be an upstream JSSC bug.

https://github.com/java-native/jssc/blob/master/src/java/jssc/SerialPort.java#L53

(This link is an upstream JSSC fork we maintain, upstream JSSC has not been updated in several years).

**Comment by tresf** [comment]
Upstream bug report created here: https://github.com/java-native/jssc/issues/58

I've added the code to the JSSC API, but getting a fresh build of JSSC built for the many platforms that library supports is a considerable effort, so will need to happen later this week (and then we can bump QZ Tray's code, then release a patched version with this baud).

**Comment by furqan56** [comment]
Thanks man, you guys are doing great job!

**Comment by tresf** [comment]
Closed via https://github.com/qzind/tray/commit/ddb65ba47c4c2c8e37a46018140d641b2800cd37.  Available since 2.1.4, 2.2.0.

**Comment by tresf** [comment]
Turns out this has been broken all along, reported again in #1211.  Although we've satisfied the JSSC requirement, we have the values copied into [`SerialUtilities`](https://github.com/qzind/tray/blob/24a06c24b338febdb50963ad381aa20e56663609/src/qz/utils/SerialUtilities.java#L29C1-L35) and it's missing there.
