### ISSUE TITLE
Arabic printing

### ISSUE THREAD

**Issue by janet1978** [qzind/tray#519]
Printer (Vectron) prints arabic correctly but from vb.net application using QZ tray it print the same as question marks

**Comment by tresf** [comment]
How is .NET printing?  If it's not raw, it's not the same technique.  Please share sample code.

**Comment by janet1978** [comment]
builder.Append("\r\n" + itemname + aname.ToString + " ")

Here i am printing itemname in English and Arabic . Its called from database and i can see it in correctly in the variables. see the below screen . but when printing to qz printer it displays as question mark

![arabic](https://user-images.githubusercontent.com/57855568/69004300-96b5e180-092a-11ea-984f-9f2fe7b07865.gif)

**Comment by janet1978** [comment]
![image](https://user-images.githubusercontent.com/57855568/69004385-c9140e80-092b-11ea-93a1-f91b5c93b6a7.png)

please find the receipt

**Comment by tresf** [comment]
I'm sorry, I misunderstood.  I thought based on your original bug report that you had Arabic printing using another technique.

Arabic is very tricky in ESC/POS because not all printers honor it equally.  For example, some printers support RTL, others only support LTR.

Here is our tutorial for sending Arabic.  If this prints backwards, we may need to change code for this to work.

https://qz.io/wiki/Raw-Encoding#escpos-arabic

**Comment by janet1978** [comment]
No still prints as question marks :(

**Comment by tresf** [comment]
We'll need more information about the hardware.  What make and model is the printer?  What codepage does it support?  For example, our current Arabic example uses a very old encoding called `IBM864`.  If the printer does not support this, the example won't work.

**Comment by janet1978** [comment]
It is Vectron(Metapace)Model: Metapace T-3II
    On Monday, 18 November, 2019, 06:47:29 pm GMT+4, Tres Finocchiaro <notifications@github.com> wrote:  
 
 
We'll need more information about the hardware. What make and model is the printer? What codepage does it support? For example, our current Arabic example uses a very old encoding called IBM864. If the printer does not support this, the example won't work.

**Comment by tresf** [comment]
I've emailed Metapace asking if this is supported.

- Tres.Finocchiaro@gmail.com

**Comment by janet1978** [comment]
Thanks.

**Comment by janet1978** [comment]
Any updates you have
    On Tuesday, 19 November, 2019, 10:17:13 pm GMT+4, Tres Finocchiaro <notifications@github.com> wrote:  
 
 I've emailed Metapace asking if this is supported.

- Tres.Finocchiaro@gmail.com

**Comment by tresf** [comment]
No word from Metapace.  It may be better to wait for #522 so we can just skip the hardware-specific stuff.

**Comment by tresf** [comment]
@janet1978 still no reply.  I've emailed them again with the same question.  If they don't get back, I'm not sure what else can be done.

Note, if you have a programming manual for this please share as we're finding that Epson "clones" sometimes use different code pages.

**Comment by tresf** [comment]
@janet1978 I'm closing this because Metapace never offered any reply about Arabic support.

However, we have improved our HTML->RAW ESCPOS printing capabilities and they may work well for your needs.  There's a bug with 2.1.1 preventing them from working properly and the fix is currently on a branch that has not been merged yet.  This will likely be your best option unless Metapace has another support channel we can reach out to.

I'm closing this in favor of #675 for now, as using HTML to print Arabic to these printers is probably the best avenue.
