### ISSUE TITLE
Exceptions thrown in openConnection deadlock API

### ISSUE THREAD

**Issue by tresf** [qzind/tray#544]
Discovered while working with #543, I found that the API deadlocks if certain exceptions are raised in `openConnection`.

https://github.com/qzind/tray/blob/ffc94993ea40cba483d53e10c4e7f94237c9e8b6/js/qz-tray.js#L176

To reproduce, change the following:

```diff
                        // track requesting monitor
                        obj.position = {
-                            x: typeof screen !== 'undefined' ? ((screen.availWidth || screen.width) / 2) + (screen.left || screen.availLeft) : 0,
-                            y: typeof screen !== 'undefined' ? ((screen.availHeight || screen.height) / 2) + (screen.top || screen.availTop) : 0
+                            x: screen2 ? ((screen.availWidth || screen.width) / 2) + (screen.left || screen.availLeft) : 0,
+                            y: screen2 ? ((screen.availHeight || screen.height) / 2) + (screen.top || screen.availTop) : 0
                        };
```

**Comment by bberenz** [comment]
Issue looks to be caused by an exception being thrown outside of the promise callback and outside of the try block in that particular function, so a reject on the promise is never performed causing the promise to hang indefinitely.
But with the fix to the screen reference check I don't believe it will be an issue going forward since the remaining references are all internal and if they don't exist we have a bigger issue.
(If it does prove to be an issue, wrapping the code inside the `_qz.websocket.connection.onopen` function in a try/catch that properly rejects on an exception should be sufficient.)
