### ISSUE TITLE
Use of external API call

### ISSUE THREAD

**Issue by tresf** [qzind/tray#545]
Brett, this looks like it sneaked in #348.  Shouldn't this use an internal API call?

https://github.com/qzind/tray/blob/f27a56261f2df3fee0a07506c76669fcb56664d6/js/qz-tray.js#L321-L323

**Comment by bberenz** [comment]
We seem to have a few spots where we do this, such as with `isActive` and even one to `print`.
So I've just made the public object have an internal `qz` reference in our private function so that regardless of the exported name, we still can use these references as they currently exist.

Available on the [reference](https://github.com/qzind/tray/compare/reference) branch.
