### ISSUE TITLE
Too long for response if RPC is not available

### ISSUE THREAD

**Issue by harikesh409** [qzind/tray#583]
If my RPC server is unable the qz tray is taking very long time to detect that and give an response is there any way to set the amount of time?
Attached the debug log for reference.
[debug.log](https://github.com/qzind/tray/files/4192101/debug.log)

QzTray Version: 2.0.3-2

**Comment by harikesh409** [comment]
Even though the RPC is unavailable qz is giving the log as found how is that possible?

**Comment by tresf** [comment]
@harikesh409 the error is being thrown by an internal Java library.  We've have a lot of errors over the years, this is the first time I've seen this.

Does it happens if you use 2.0.11 and AdopOpenJDK 11 64-bit?  What I'm reading is that this can be caused by a few things (some unrelated to Java entirely).  Furthermore, some older versions of Java had issues where the print service would get hung.

If you have more information to provide we'd love to look further, but my initial instinct is that this problem is not with the QZ Tray software.

**Comment by harikesh409** [comment]
The problem occurs only when I am using the spooling option and on using with AdopOpenJDK the issue is not reflected, so the issue is with Java only. Thank you.
