### ISSUE TITLE
Support to align qr and text.

### ISSUE THREAD

**Issue by alexandrox92** [qzind/tray#603]
It would be great to be able to pull something like this.

![Image of Yaktocat](https://i.ibb.co/FV7MmDn/Whats-App-Image-2020-03-09-at-6-03-47-PM.jpg)

Currently the QR code and images can only be printed on defined lines.

**Comment by tresf** [comment]
Epson wrote ESC/POS quite a while ago, it's unlikely they'll ever add such a feature.

You can use HTML, PDF or image to print and achieve this, but I'm not aware of a way that ESC/POS supports this.

Since ESC/POS uses the printer's default font, it's often preferred over HTML, PDF, Image.  Some printers support the concept of roll-back (for printing the same area twice) but it's been removed from many firmwares due to the tendency to jam a printer.

For those reasons, I'm not sure this is possible.  Even if it were, it would be an ESC/POS solution (not necessarily a QZ Tray solution), so it wouldn't necessarily be a change to our product, but perhaps our wiki.

For those reasons I'm inclined to say this is not our bug.  I'll leave it open for a bit for further comments before closing.

**Comment by alexandrox92** [comment]
It is good to have this clear, thank you very much.

printing using html implies a fairly large change in when the print order is given, in addition the QR must be generated as an image and qztray usually has problems constantly when I print images (here an example)

https://imgfz.com/i/bx8C6AO.jpeg  and https://imgfz.com/i/trmqJi1.jpeg

in any case thank you very much,

Closed

**Comment by tresf** [comment]
>  qztray usually has problems constantly when I print images (here an example)

This should probably be a separate issue, but are you sure that the image isn't too wide for the receipt paper?  Printer widths and dpi vary and you should put image size restrictions to prevent overflow.

If an image that's not wider than the paper is still causing a problem, we can work from a dedicated bug report.

> printing using html implies a fairly large change in when the print order is given

Agreed.  I don't love this recommendation, but due to other problems with ESC/POS (such as international character support) the Pixel formats are getting more popular as time goes on.
