### ISSUE TITLE
Printer Emulators Wiki - corrections

### ISSUE THREAD

**Issue by RWAP** [qzind/tray#613]
In the Wiki (Printer-Emulators) section, you refer to QPCPrint as a raw printer.  That is correct, but it only handles ESC/P2 not ESC/POS.

You might also like to include my own Retro-Printer hardware (www.retroprinter.com) and its C based ESC/P2 raw printer convertor PrinterToPDF (https://github.com/RWAP/PrinterToPDF)

**Comment by tresf** [comment]
> In the Wiki (Printer-Emulators) section, you refer to QPCPrint as a raw printer. That is correct, but it only handles ESC/P2 not ESC/POS.

Corrected, thanks.

> You might also like to include my own Retro-Printer hardware (www.retroprinter.com) and its C based ESC/P2 raw printer convertor PrinterToPDF (https://github.com/RWAP/PrinterToPDF)

This looks very useful.  The emulator page is intended to offer developers a software emulator when hardware isn't available.  A quick, installable CUPS (or Winspool) printer would be a good candidate, we'd love to add it if it becomes available.  Due to the barrier to entry (compiling C, editing header files) and lack of [downloadable software](https://github.com/RWAP/PrinterToPDF/releases) we won't be adding it at this time, but we'll make sure to recommend this in the edge-case that it's requested.

Note, at the time of writing this, Linux is about 3% of our downloads (Windows is 83%, MacOS is 12%).  Popularity is split about 50/50 ways between Raw (ESC/POS and ZPL) and 2D printing methods like PostScript, PDF, etc.  ESC/P is a very, very small subset of our raw printing.  Those users with the ambition to compile C on Linux for purposes of talking ESC/P to a non-printer would be too much of an edge-case, but we'd love to offer it if a simple, compatible technique is made available. 🍻

**Comment by tresf** [comment]
I also invite you to reach out directly for future map discussion, overlap or other technical or business commonalities tres@qz.io 🍻
