### ISSUE TITLE
Suggestion: Breakup projects

### ISSUE THREAD

**Issue by corbinu** [qzind/tray#62]
Hello,

I am interested in your project however it seem like there are really 5 projects in this repo

- QZ Tray lib
- QZ Server
- JavaFX UI
- Installer builder
- JavaScript client

I was wondering if you would be interested (and I would be happy to help just wanted to make sure there was an interest before I started doing work) in breaking it up into a set of repos. It seems like this would be relevant to issue #51, issue #13 and issue #44 

I would prepose the following set of repos:
- qz_tray_lib that is a jar with the main code
- qz_server which would be the headless product for #51 
- qz_tray_gui with all the JavaFX code
- qz_tray_nsis which would generate an installer for the 3 above companied as currently
- qz_tray_wix which would build the new MSI installer for #44 
- qz_js_client which would simply contain the current JS code (I would be happy to update it so that it is easy to consume via bower & npm #13)

As a note I would probably build my own install builder on http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGIBBCI

But thats the nice thing about this new structure is that could be maintained by me and if nobody else uses it who cares.

**Comment by tresf** [comment]
> As a note I would probably build my own install builder on http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGIBBCI

If HTTPS is required, I don't believe this will work.  You'll need a platform-specific installer to shim the certs for the OS/Firefox.  Please enlighten me if I'm incorrect here.

> qz_tray_gui with all the JavaFX code

You mean Swing code?  We don't have much Java FX code so I'm confused by this statement.

> qz_tray_wix which would build the new MSI installer for #44

Using what exactly, git submodules?  Not a fan personally, they add unnecessary steps to the build process in my opinion, especially for smaller projects.

> qz_js_client which would simply contain the current JS code (I would be happy to update it so that it is easy to consume via bower & npm #13)

Since I've never run a purely JS repo before, can you explain the advantages of a separate JS repo over the existing design?

> qz_server which would be the headless product for #51

I assume this would use git submodules?

> qz_tray_nsis which would generate an installer for the 3 above companied as currently

Well, we package for Apple and Linux too.  What would you make more repos?


I'm intrigued by the request although I'm not sold on the idea.  It seems like it would add an unnecessary amount of overhead with little gain, but I'm willing to take time to understand your thought process.

**Comment by corbinu** [comment]
> As a note I would probably build my own install builder on http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGIBBCI
If HTTPS is required, I don't believe this will work. You'll need a platform-specific installer to shim the certs for the OS/Firefox. Please enlighten me if I'm incorrect here.
My understanding is the scripts should be able to be injected for example the Ant script from Oracle that generates the Windows installer is WiX and supports all the customizations therein (I believe the same is true for OS X pkg, deb and rpm

If it doesn't work is fine just was an example of how breaking things up made it easier for other developers to customize

> qz_tray_gui with all the JavaFX code
You mean Swing code? We don't have much Java FX code so I'm confused by this statement.

Yes sorry I thought 2.0 was all rebuilt in JavaFX from skimming the docs yes all GUI code

> qz_tray_wix which would build the new MSI installer for #44 Using what exactly, git submodules? Not a fan personally, they add unnecessary steps to the build process in my opinion, especially for smaller projects.

Well I am not a fan of submodules I would say it would probably be an ant or gradle task which could pull the gui and server jars from either github releases or from maven. I guess I may have gotten a little used to the Node philosophy of keeping everything broken up like Unix. Keep all the versioning/testing/modifications separated. That way somebody who just knows printers for example isn't like "well whats NSIS and Wix" when the come to the repo just looking to add printer support to the qz_tray_lib.

> qz_js_client which would simply contain the current JS code (I would be happy to update it so that it is easy to consume via bower & npm #13)
Since I've never run a purely JS repo before, can you explain the advantages of a separate JS repo over the existing design?

Well the big thing here is that the developers who would want to help with the JS side are probably rarely the developers who want to help on the Java side. So I tend to try to break up projects especially if they are in different languages. Honestly this is probably the split I would recommend above all the rest. (even though I personally might just end up only using the qz_tray_server) 

Bower especially and NPM also generally expect a module to be a repo. Somebody trying to pull the JS module down via bower for use in their web app probably doesn't need or want all the Java code getting cloned too (obviously you can use .npmignore) but bower will still be an issue.

> qz_server which would be the headless product for #51
I assume this would use git submodules?

No this one especially I would say should be built to a Jar and released that way somebody looking to download the app for their Raspberry Pi doesn't need to pull down a fat installer can just download the jar and run it if they so choose

> qz_tray_nsis which would generate an installer for the 3 above companied as currently
Well, we package for Apple and Linux too. What would you make more repos?

No I am suggesting a break up by project not end artifact. It appears that NSIS builds for all three platforms so that would be one project/repo with 4 build artifacts per version (Windows, OS X, deb, rpm)

> I'm intrigued by the request although I'm not sold on the idea. It seems like it would add an unnecessary amount of overhead with little gain, but I'm willing to take time to understand your thought process.

I understand and maybe not breaking it up so much would be better. I just know sometimes people are more likely to contribute if they understand a repo fully. Also my first thought when coming to the repo was "wow there is a lot here I don't need" even though it also looked really cool. 

maybe a better set would simply be 

- qz_tray_server (jar published to maven for headless or library use)
- qz_tray_gui (includes in the installer published as currently)
- qz_tray_js (published to npm/bower)

True there can be some overhead but it should be pretty easy to automate with ant and travis.

**Comment by tresf** [comment]
> No this one especially I would say should be built to a Jar and released that way somebody looking to download the app for their Raspberry Pi doesn't need to pull down a fat installer can just download the jar and run it if they so choose

This statement makes me think you're confusing where the bloat comes from.  The project source is quite small from a compiled-byte standpoint, but the size gets inflated with the various 3rd party libraries we use.  For example, the Jetty WebSocket libraries weight in over 3MB.  JFXRT (not needed for install, but used for fixing compilation on OpenJDK) is a whomping 14.7MB.  Add in PDF, USB and Serial libraries and the build dependencies are 30MB.

So I think I understand the motive behind your request, but perhaps if we address the use-case you're describing (e.g. minimum build) it would help.  For example, if you want a raw-only websocket server without the cruft imposed by the additional features, perhaps that would be a more attainable goal rather than splitting a small project into several interdependent projects.

I'm not dismissing the fact that
 1. The JS library could benefit from being in npm (i.e. #13)
 2. We could drastically reduce our repo size by leveraging maven for 3rd party libraries
 3. Getting involved with a mixed-code repo can be daunting

However I personally cringe at the idea of updating two separate repos for a single API change and I have a hard time understand why a Wix installer script warrants a separate repo.

As you've stated, the npm stuff can be tackled without the change and the GUI/server stuff I just don't understand the benefit of.  The swing code is quite minimal and once we decouple them, the existence of GUI calls would be benign when one doesn't exist and when one does, we could consider providing a way to force it off.

I hope this isn't read as dismissive however I'm quite happy with the efficiency of the build process and complicating that would have to be better than what it is today or alternately have merits that outweigh the burden such a change would cause to the build process.

**Comment by tresf** [comment]
Also worth mentioning, we use `makeself` for our installers, so you can easily avoid installation by using the `--extract` option with the Linux desktop installer and blowing away anything you consider to be non-critical (such as the demo folder).

**Comment by corbinu** [comment]
@tresf No worries about sounding dismissive it is your project I will just say my concerns were much more centered around ease of introduction for more contributors not from the perspective of the install being to large. Striping it down for my own use is fairly simple (just fork ... strip out everything not needed and then simply PR any enhancements I make to those files and pull any updates from your side). 

I am not sure what you mean though by "updating two separate repos for a single API change" it seems like the interaction API is very abstracted away and I have usually found as long as semver is followed properly that you would either be making changes for example in the GUI ... or how the JS lib is used... or adding a new printer. Not modifying how the 3 components speak to each other.

Actually maybe the Wix installer is a perfect example of why people break it up this way. It lets you create a new project ... build and test it in production. Let other people easily contribute. Then if it comes to point where it supplants the NSIS installer that repo simply is left for legacy reason and the Wix one is linked to for windows install in the documentation. As I think I stated before I am coming from the Node.js world which bases its concept of small models that each to one thing on Unix. Somebody creates SH... everybody loves it.. then somebody has a better idea for Bash ... once that became stable it supplants SH, but as long as somebody is willing to maintain it no reason to remove SH. 

Anyway going to close, but would defiantly still recommend you pull out the JS lib.

**Comment by tresf** [comment]
> I will just say my concerns were much more centered around ease of introduction for more contributor

Hmm... interesting.  We've had very little contributions out of good will, probably because we're tailored so specifically for revenue generating outfits (shipping, POS) that many clients would rather just pay for support and ask us to fix it.

For those that do get involved in the code, maintaining a single JS file has been OK.  We get quite a few requests to be on NPM, but that's not really related.  Perhaps the semantic versioning could state that it is (e.g. if qz-tray.js doesn't change, why bump it's version) but we could get creating and make hooks to prevent that.

> I am not sure what you mean though by "updating two separate repos for a single API change" it seems like the interaction API is very abstracted away and I have usually found as long as semver is followed properly that you would either be making changes for example in the GUI ... or how the JS lib is used... or adding a new printer. Not modifying how the 3 components speak to each other.

I'm still not understanding the GUI portion you keep mentioning.  We rarely change the GUI, but the websocket messaging is more volatile as we add new features.  For example, we'll soon be adding HID support as well as better printer statuses.  Those are API changes and will require changes in both the JavaScript as well as the Java code base.  We could certainly track them in separate repos, but they are mutually inclusive to each-other.  The JS relies on the Java feature being there.  The Java feature is worthless without a JS lib capable of calling it.

> Actually maybe the Wix installer is a perfect example of why people break it up this way. It lets you create a new project ... build and test it in production. Let other people easily contribute. Then if it comes to point where it supplants the NSIS installer that repo simply is left for legacy reason and the Wix one is linked to for windows install in the documentation. 

Hmm... This is all part of a standard GitHub Fork/Pull Request process in my opinion (see HID branch) and the documentation part is always a follow-up task. (not to be confused with the API documentation which is automatically checked in as part of the JSDoc generation)

In our case, the wiki is generally maintained by our support staff, which is who fields the calls that are in some ways a direct effect of the quality of our tutorials.  If we burdened the developer with this task, quality and knowledge transfer could both suffer (e.g. what incentive does the developer have in writing a good wiki if it only helps out the support crew)

But back on topic... I'll let @bberenz chime in with his thoughts on the structure of things as he's helped architect the switch from LiveConnect to WebSockets as well as the new API namespace, etc so his opinion is likely more valuable than my own. :)

**Comment by tresf** [comment]
> As I think I stated before I am coming from the Node.js world which bases its concept of small models that each to one thing on Unix. Somebody creates SH... everybody loves it.. then somebody has a better idea for Bash ... once that became stable it supplants SH, but as long as somebody is willing to maintain it no reason to remove SH.

Yes, the desktop software world tends to suffer the "everything" problem and we're definitely susceptible to that problem, but it's not necessarily a bad thing but I don't think you're talking about features here really, right? (if that's the case, 1.9 versus 2.0 did what you're describing).  Instead I feel you're talking about submodules.  We have components and they all rely on a centralized core (the WebSocket server).   Decoupling them would allow each component to operate separate from itself and in large projects (e.g. PDFBOX) they are decoupled using Maven and we certainly may find benefit in doing that.  The difference is that larger projects often compartmentalize with the purpose/incentive of re-use.  In our case, I don't know what good our small amount of GUI code would be without the WebSocket code, or what good the JS would be without the WebSocket code.

> Long term I plan to have something similar to Google Cloud Print or PrintNode. Using QZ's Java code to talk to the printers, however all the jobs will be communicated via Couchbase-Lite. The print server will be headless and there will be a totally separate GUI apps that shows the pending print jobs and allows them to be canceled, retried etc. No WebSockets, Swing or JavaFX so jobs can easily spread jobs across multiple print servers and be managed either from the Electron App, iOS or Android app or in browser.

Well that makes quite a bit more sense I feel.  If that's the case, please feel free to add a custom ant task to build only the components you need.  We used to write our printing library as a Java API (Google Code days), but in all of the years it's been around we've had only a few (I think 3 people) use it as a raw API.  The rest (thousands) all use it off of the shelf, so we stopped doing that.

If you don't mind me asking, which components from the printing side do you find valuable enough to import?  Furthermore, if there are any code bindings that don't make sense from a Java package perspective, please open issues on them as (like you stated) they'll only help contributors find the code quicker. 👍

**Comment by corbinu** [comment]
> Yes, the desktop software world tends to suffer the "everything" problem and we're definitely susceptible to that problem, but it's not necessarily a bad thing but I don't think you're talking about features here really, right? (if that's the case, 1.9 versus 2.0 did what you're describing). Instead I feel you're talking about submodules. We have components and they all rely on a centralized core (the WebSocket server). Decoupling them would allow each component to operate separate from itself and in large projects (e.g. PDFBOX) they are decoupled using Maven and we certainly may find benefit in doing that. The difference is that larger projects often compartmentalize with the purpose/incentive of re-use. In our case, I don't know what good our small amount of GUI code would be without the WebSocket code, or what good the JS would be without the WebSocket code.

No for sure it was pretty easy for me to figure out what features I need and the code is well structured. Maybe I underestimate the average coder to know what to do when they old need part of a repo and then how to contribute back.

> Well that makes quite a bit more sense I feel. If that's the case, please feel free to add a custom ant task to build only the components you need. We used to write our printing library as a Java API (Google Code days), but in all of the years it's been around we've had only a few (I think 3 people) use it as a raw API. The rest (thousands) all use it off of the shelf, so we stopped doing that.

Ya if there is an "easy way" for some reason I am one who always has to do it "my way" I defiantly can set up an ant task that just builds a Java API lib. And you defiantly have to let the customers dictate the path :)

> Of course not. At a quick glance I would probably use the following:
tray/src/qz/communication/
tray/src/qz/exception/
tray/src/qz/utils/
tray/src/qz/printer/ minus HTML (I will use PDF.js to covert to PDF)

Looks like I will need to reimplement tray/src/qz/ws/PrintSocketClient.java
To instead process the jobs that are in the local DB.

Will defiantly open issues and/or PRs if I see something that might help (or long term if my project works out just PR a Wiki page for using the JavaAPI)
