### ISSUE TITLE
self signed certificate - dosent work OpenSSL

### ISSUE THREAD

**Issue by thbl** [qzind/tray#629]
Trying to get QZ to work with self signed cert but dosent seam like QZ is loading my cert :/

Made cert with
```
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 11499 -nodes
openssl pkcs12 -inkey key.pem -in cert.pem -export -out privateKey.pfx
```

After this i used this command
```
java -jar qz-tray.jar certgen --key "key.pem" --cert "cert.pem"
java -jar qz-tray.jar certgen --pfx "privateKey.pfx" --pass "password"
java -jar qz-tray.jar certgen --host "127.0.0.1"
java -jar qz-tray.jar certgen --hosts "localhost"
```

Am i missing something ? does any one etc. have a quick guide on how to self sign

**Comment by tresf** [comment]
Are you trying to use the cert for SSL or for bypassing the licensing?

We don't offer help with bypassing the licensing, but I can tell you the commands you're using are for the SSL component.  Licensing is provided as `override.crt`, per signing messages tutorial.

**Comment by thbl** [comment]
for bypassing licensing, as its just for a small local hobby project and the pop up warning is so annoying :b

**Comment by thbl** [comment]
@tresf is it possible to remove / igonore the popup for localhost ?

**Comment by tresf** [comment]
You can stub-out the code that raised the dialog if security's no concern.  It's called `GatewayDialog`.

If you want it to be secure, shimming that `override.crt` certificate is the way to go.

We've had a policy of not assisting with this, @lite1979 and I work full time on this project and we'd otherwise have no job if everyone bypassed the licensing.

**Comment by tresf** [comment]
Documentation on `override.crt`: https://qz.io/wiki/signing-messages#advanced

**Comment by tresf** [comment]
> is it possible to remove / igonore the popup for localhost ?

We need to add a feature to disable the pop-up for that session, even our paid clients need this for when a technical issue occurs and the signing isn't working.   We'll likely be adding this in a future release.

Well also be offering a perpetual licensing model in the future so companies don't have to worry about annual renewals.  That's a bit tougher though, requires a custom build per-customer.

**Comment by tresf** [comment]
Here's a one-liner to suppress the dialog.  Note, this is a major security concern and should only be used for testing.  When deployed to production, you should self-sign the messages per the original question using the `override.crt` method.

Note, self-signed QZ Tray instances are the MOST secure because you're the only one capable of providing a valid key for signing. 

```diff
    public boolean showGatewayDialog(final RequestState request, final String prompt, final Point position) {
+        if(true) return true; // WARNING: Insecure! Allows any device to read from USB, Serial, Get Network Info, Get Printer Info
```
