### ISSUE TITLE
security risk: "print to file" can write any file that the qz_tray user has access to, anywhere in the file system

### ISSUE THREAD

**Issue by alterlife** [qzind/tray#631]
When printing to file, there's no validation on the path of the file. This means that you can print to (and effectively overwrite) any file that the user has access to.

I think this is a security risk. You can for example write to a file in the users home directory like .vnc/passwd or overwrite files in the documents folder. A much more terrible fate if the qz-tray appilcation has been run as root.

Note that I'm talking about the print to file option: https://qz.io/wiki/2.0-raw-printing#print-to-local-filesystem

There's another feature in qz 2.1 which allows file access: https://qz.io/wiki/2.1-file-communication appears to validate that write be limited to directories in a strict whitelist, which seems to work correctly though I wish there were a way to turn this off as well if it's unused!

**Comment by tresf** [comment]
> When printing to file, there's no validation on the path of the file. This means that you can print to (and effectively overwrite) any file that the user has access to.

Not any file, but yes any location.  Early precautions were taken to blacklist most common file types.  This list can be expanded.

`printToFile` is a really old feature and should be eventually be crippled or removed since we have newer, better ways of writing files.

Note with that said, all print requests must be digitally signed.  QZ Tray -- in it's very nature -- provides access to things things blocked by browser security.  For this reason, operations can be perceived as security risks, which is why digital signatures are required for every operation.

Furthemore... what's important and worth noting but not mentioned in the original bug report is that `.vnc/passwd` [uses insecure password storage, a major design flaw given the widespread use of VNC](https://linux.die.net/man/1/vncpasswd).  It's been the target of remote exploits for many years.

A regression we need to be concerned about when removing `printToFile` is how it's often used for [UNC paths for writing raw data to shared printers](https://qz.io/wiki/2.0-Raw-Printing#print-to-win32-unc-path), so removing or crippling it needs to be done in a respectful manner to its usage.

> There's another feature in qz 2.1 which allows file access: https://qz.io/wiki/2.1-file-communication appears to validate that write be limited to directories in a strict whitelist, which seems to work correctly though I wish there were a way to turn this off as well if it's unused!

Probably best for a separate bug report.

**Comment by alterlife** [comment]
If I can make a suggestion, perhaps the whitelist that's being used for the 2.1 feature could be used with the "print to file" feature as well. It's good to have tight control over where this process can write vs giving it free reign over the filesystem. 

People make mistakes while configuring almost any solution, so my opinion is always that it's better to err on the side of caution.

**Comment by tresf** [comment]
Initial deprecation notice added via 80bd7ae, will be available starting with qz-tray.js 2.1.3.  Issue to track the steps to carefully deprecate this feature filed here: #730, which supersedes this issue.  I believe all requests have been addressed over there, feel free to chime in if I missed something.

> There's another feature in qz 2.1 which allows file access: https://qz.io/wiki/2.1-file-communication appears to validate that write be limited to directories in a strict whitelist, which seems to work correctly though **I wish there were a way to turn this off as well if it's unused!**

If this is still important, please file a separate bug report and please provide a use-case where the existing File IO behavior needs a hard toggle-off.   A similar argument is made in #78 about device access however, that's unfettered and doesn't have the luxury of a sandboxed design like File IO.
