### ISSUE TITLE
How to setting timeout printing

### ISSUE THREAD

**Issue by showzhou1** [qzind/tray#687]
The user turned off the thermal printer during the order printing process, but the current printing has not been completed.
If the thermal printer restarts within `10` seconds, the current remaining content will continue to print.

How can i extend this time

extra information：
qz-tray  version:`2.1.1+1`
openjdk version:`11.0.7`

**Comment by tresf** [comment]
Which OS?  I assume the OS has a spool retry period but we've never tested to that granularity.

**Comment by showzhou1** [comment]
very sorry,
Operating system is `Windows`

**Comment by tresf** [comment]
If the driver supports, it there should be an option called "Transmission Retry" or "End of Print Timeout", etc.

* For Epson's driver, it's 150 seconds
* For and LPT port it's 90 seconds

Since the driver appears to have control over this option, that's the best place to set it.  If you find a way to do this for all drivers and operating systems through Java, we'd be happy to add the feature.

Since this is driver-specific, we'll likely close this bug report as wont-fix.

<img width="304" alt="Screen Shot 2020-07-03 at 11 48 17 AM" src="https://user-images.githubusercontent.com/6345473/86484002-39d53300-bd23-11ea-839e-3b9fe6069b03.png">

<img width="447" alt="Screen Shot 2020-07-03 at 11 48 34 AM" src="https://user-images.githubusercontent.com/6345473/86484038-4bb6d600-bd23-11ea-8454-d71f31e6f658.png">

**Comment by tresf** [comment]
> Since this is driver-specific, we'll likely close this bug report as wont-fix.

Closing.
