### ISSUE TITLE
2 issues with image printing

### ISSUE THREAD

**Issue by robisoft** [qzind/tray#712]
When I print an image followed by other esc/pos data, qz cuts the receipt after image (issue) and also at the end (correct).
This occours with Espon TM/TII20.
The image is not printed at all with MUNBYN esc/pos printer.
Can someone help me?

**Comment by tresf** [comment]
@robisoft can you please provide a reproducible code snippet so that we can take a look?  There two main ways to send an image: Pixel and Raw.  The Pixel method will honor your driver settings, which may have a cut command in the preferences.  The Raw should not.  Your usage should help explain what's going on so that the code -- or if needed QZ Tray -- can be corrected.

> The image is not printed at all with MUNBYN esc/pos printer.

It would be best to have a separate support issue for this, since it seems to be unrelated.  Can you change the title of this to reflect one issue and then open a second issue on printer compatiblity?

**Comment by robisoft** [comment]
Thank you for you quick answer. Using only { type: 'IMAGE', data: path } give me the issue, but this works spectacularly:
{
        type: 'RAW',
        format: 'IMAGE',
        data: path,
        options: {
          size: { width: 2.7, height: 1.5 },
          units: 'in',
          language: 'ESCPOS',
          dotDensity: 'double',
          xmlTag: 'v7:Image'
        }
}
