### ISSUE TITLE
Silent uninstall issue

### ISSUE THREAD

**Issue by AbuHadjar** [qzind/tray#713]
Hi,
During preparing script for silent deploy, Ive noticed, that version qz-tray-2.1.1+1 and newer ignore usage of "[install_dir]uninstall.exe /S"
On version 2.0.12 it's working perfectly.

**Comment by tresf** [comment]
This appears to be a regression introduced with #614.

**Comment by tresf** [comment]
The bug seems to occur in the respawn logic here: https://github.com/qzind/tray/blob/59f0f7ac7b40c733b36c0138ff2753687f7d2edc/ant/windows/windows-uninstaller.nsi.in#L100

... as the respawn logic never re-passes the `/S` silent flags to the new instance.  Note, a temporary workaround is to do the following:

```cmd
set qz_silent 1
uninstall.exe
```

Per https://github.com/qzind/tray/blob/59f0f7ac7b40c733b36c0138ff2753687f7d2edc/ant/windows/windows-uninstaller.nsi.in#L63.  Caution, the environmental variable flag is internal, undocumented and subject to change, so it should only be used as a temporary workaround until this issue is resolved.

**Comment by tresf** [comment]
Ok, turns out this isn't an oversight at all, just a bug.  Take the following line, which sets **`qz_silent`**

https://github.com/qzind/tray/blob/59f0f7ac7b40c733b36c0138ff2753687f7d2edc/ant/windows/windows-uninstaller.nsi.in#L63

... and then this line looks for **`qz-print_silent`**

https://github.com/qzind/tray/blob/6d7f1f303ba7e0dbe520b2fb4529abd0ff960a96/src/qz/installer/Installer.java#L45


which suggests that this is broken for install and uninstall.  Still investigating.

**Comment by tresf** [comment]
There's more bugs.  Apparently I clobber the environmental variable even if it's set properly.  Working on a patch now.

**Comment by tresf** [comment]
@AbuHadjar can you please test out this installer? https://github.com/tresf/tray/releases/download/v2.1.3-RC/qz-tray-2.1.2+3.exe

**Comment by AbuHadjar** [comment]
> 
> 
> @AbuHadjar can you please test out this installer? https://github.com/tresf/tray/releases/download/v2.1.3-RC/qz-tray-2.1.2+3.exe

now its working perfectly- thanks!

**Comment by AbuHadjar** [comment]
I overlooked, there are still leftovers in [InstallDir]. however, no window was shown during uninstall.

**Comment by AbuHadjar** [comment]
![cmd](https://user-images.githubusercontent.com/71769138/94122524-f3d7c900-fe52-11ea-9251-78d7c227f80d.png)
![log](https://user-images.githubusercontent.com/71769138/94122528-f4705f80-fe52-11ea-8060-698ffb84a160.png)
Please see screenshots - I've tried to uninstall it in System Context.

**Comment by tresf** [comment]
@AbuHadjar we've never performed an uninstall as System user before, can you please **open a new bug report with the full logs**?  We'll have to guard against certain folders when running as a non-interactive user however this is a separate issue and should be filed as such.

**Comment by tresf** [comment]
@AbuHadjar I was able to reproduce the issue, investigating now... #717
