### ISSUE TITLE
Add certificate specifications in documentation

### ISSUE THREAD

**Issue by Simon-Boyer** [qzind/tray#799]
Hello!

When using a custom trusted root and whitelisting a certificate from the command line, there seems to be some information missing from the documentation. 

First, the certificate needs a FQDN (that one is obvious) and an Organization name (this one is less obvious). I had a certificate laying around that I used to test the software and I wasn't able to make it work for while because it didn't had the Organization name set.

Secondly, the `digital-certificate.txt` file needs to have the line `--START INTERMEDIATE CERT--` between the certificate and the intermediate certificate, but that's not a requirements of the X.509 format. this specification should also be added to the documentation.

In general, I think the custom certificate configuration / headless deployment documentation could have a little more "meat", as it is the case when using the QZ Industries signing service.

Thank you for the good work, now that I actually managed to whitelist my certificate it looks like a great software!

**Comment by tresf** [comment]
Historically, custom certificates were deliberately obtuse to encourage leveraging our portal.

Starting with QZ Tray 2.1.3, we're finally changing our stance.

You're right, the intermediate text is non-standard however instead of documenting the problem forever, it would be pragmatically better to just remove this non-standard requirement.

Furthermore there are some problems with self-signed certificates that have been largely solved with #708, which offers the self-signed certificate capabilities as a drop-down in the Site Manager dialog.

If there are specific bugs with empty fields, I'd ask that we compare the x509 spec and make decision to fix it or justify and document it, each probably with it's own bug report (or a meta report with defined items).

**Comment by Simon-Boyer** [comment]
Yes, I`m pretty sure there is tools or libraries in java that could be used to read the certificate chain other than doing a `.split()`. I'm pretty sure that you could use the Bouncy Castle APIs to do that.

For the empty fields, I tried to read the X.509 RFC, but I'm really confused of what is required and what is not. I would think that the CN is required and the Organization isn't (iv successfully used the certificate without organization for HTTPS hosting) but I'm not sure.

It seems like it's the only 2 fields used (other than validity, public keys and things inherent to a certificate), at least it's what I see in this file [](https://github.com/qzind/tray/blob/master/src/qz/auth/Certificate.java)

**Comment by tresf** [comment]
Most CAs mandate organization, but if that crashes the software we can fix that, let's start with a dedicated bug report and go from there.

In regards to the chained certificates, I doubt many people will e doing that for self-signed, but if we can document that in a bug report too, that would be the best way to track it.

Since QZ's certificates started as a Premium-Only option, switching back to a saner, more standard true x509 is going to take some time, but any quick wins or obvious pitfalls are welcome to be documented.

For example, our CRLs are proprietary (or more accurately, non-standard).  This requires turning the proper CRL feature off in Bouncy Castle and custom code.  We have a TODO to fix this, but no immediate plans.  As we embrace self-signed certs and free users more, we hope we'll get some assistance with the codebase.  If not, well tackle it between paid features. ❤️

**Comment by Simon-Boyer** [comment]
Alright! I'll make the dedicated bug reports this afternoon and maybe in the next days start looking if I can make a PR for the chained certificates. Is it only read in [src/qz/auth/Certificate.java](https://github.com/qzind/tray/blob/master/src/qz/auth/Certificate.java)? If so I don't think it would be that bad to fix, I'll probably try.

**Comment by tresf** [comment]
> First, the certificate needs a FQDN (that one is obvious) and an Organization name (this one is less obvious). I had a certificate laying around that I used to test the software and I wasn't able to make it work for while because it didn't had the Organization name set.

Organization name is no longer required per #804 

> Secondly, the digital-certificate.txt file needs to have the line --START INTERMEDIATE CERT-- between the certificate and the intermediate certificate, but that's not a requirements of the X.509 format. this specification should also be added to the documentation.

This should be resolved once #803 is fixed.

So the only parts of this that would remain relevant are the documentation.  I believe the feature to be self-documenting once the chains are working, closing.  Feel free to request re-open if I've missed something. 🍻

**Comment by tresf** [comment]
@eriktobben the override is for the cert itself, per: https://qz.io/wiki/signing#to-override-the-trusted-root-certificate, however with newer versions you just need the file in the right location, no need to edit the properties file.

Note, you can allow QZ Tray to create these as a baseline, **Advanced, Site Manager, "+", New**.  It will even copy it to the correct location for you. :)

**Comment by eriktobben** [comment]
@tresf Thank you. So if I understand you correct, I can use the Demo key or is this just to see where the key is stored?

I have two computers that will use the website, will that work with the demo key?

**Comment by tresf** [comment]
> @tresf Thank you. So if I understand you correct, I can use the Demo key or is this just to see where the key is stored?
> 
> I have two computers that will use the website, will that work with the demo key?

This bug report is specifically about certificate specifications being added to the documentation.  If you're looking to obtain support on using QZ Tray's certificates, this is probably the wrong thread for it.

QZ Tray's demo key feature is intended to work with one computer.  You may use it with more than one by deploying the cert to the other computers.  We deliberately leave these steps out to encourage getting a certificate from us.

**Comment by eriktobben** [comment]
@tresf I see that this is not the place for that.

Yes, I have noticed that these steps have been left out, and I understand why. I would gladly pay something for this great piece of software, but I can't justify $499 a year for the use case on the project I am doing now.

The ideal solution would be to have a plan around $50 and make the documentation for this feature, or have some sort of donation, as I think many small businesses are happy to pay something for good software, but not all can afford a $499 yearly cost.

Either way, thank you so much for your help :)
