### ISSUE TITLE
Does it support preview？

### ISSUE THREAD

**Issue by weiwangda2014** [qzind/tray#831]
Does it support preview？

**Comment by tresf** [comment]
Hi,

No, QZ Tray does not currently offer a "preview mode", largely due to the complexities with raw as well as the browser being unaware of Java rendering.

You may however utilize a printer emulator to preview the content, if the content is supported by an emulator: https://qz.io/wiki/printer-emulators

**Comment by tresf** [comment]
Closing, since the question was answered.  Please feel free to comment on this if you have any other questions or require a reopen.
