### ISSUE TITLE
Not Printing from printer

### ISSUE THREAD

**Issue by sanojmathew** [qzind/tray#862]
Hi,
Not printing from qz tray .Attached is the debug logs . Normal print is working fine
please advise
[debug.log](https://github.com/qzind/tray/files/7153178/debug.log)

QZ tray version - 2.1.0-RC7
Java Version - 1.8.0_301

**Comment by sanojmathew** [comment]
operating system version is windows 10

**Comment by lite1979** [comment]
@sanojmathew 

I'm sorry for the trouble you're having.

The logs indicate that the connection timed out when trying to fetch the PDF from our website. I just tested it and it seems to be working fine, so I don't believe the problem is on the website or server. 

What browser are you using?

I noticed that the connection was closed with a 1006 message as well. Please check the Site Manager in QZ-Tray to see if any certificates were blocked by accident.

I would also recommend updating the QZ-Tray to 2.1.4 (latest). We have made many changes since 2.1.0-RC7.

**Comment by sanojmathew** [comment]
Hi Thanks!

Brower is Chrome Version 93.0.4577.63 (Official Build) (64-bit)
please adivce which Java version is best suited for QZ Tray 2.14 and Windows 10

Thanks
Sanoj

**Comment by tresf** [comment]
> please adivce which Java version is best suited for QZ Tray 2.14 and Windows 10

Eclipse Adoptium OpenJDK 11 is the current recommended version.

**Comment by jjangir45** [comment]
QZ Tray not communicating between Printer & Computer

**Comment by tresf** [comment]
> QZ Tray not communicating between Printer & Computer
> Operating System - Window 10
> RAM - 4 GB
> Peocessor - Intel(R) Core(TM) i5-10400 CPU@ 2.90 GHz
> QZ Tray 2.1.4
> Java - jre-8u301-windows-x64
> Normal print working

@jjangir45 I see you have opened #867, let's please keep your issue over there unless the two are linked.

@sanojmathew the message `Cannot parse (FILE)https://demo.qz.io/assets/pdf_sample.pdf as a PDF file: Connection timed out: connect` might be a problem with Java downloading that PDF, which is often DNS or certificate related.

**Comment by tresf** [comment]
> As adviced in #862, i'v e upgraded the qz tray version to 2.1.4 and printing does not happen.
> That is why i called out as the same issue. i'll share the logs tomorrow
> But the same works fine in windows 8 machine

Your issue is a PDF not downloading, which is very specific.  The logs suggest Java cannot access https://demo.qz.io/assets/pdf_sample.pdf.  Please troubleshooting from there.  #867 does not mention PDF at all and the OP must provide more information.

Furthermore, please use the latest Adoptium Java and 2.1.4 installer and post updated logs.

**Comment by sanojmathew** [comment]
@tresf  After upgrading to  adopt jdk 11 and QZ tray version 2.1.4, printing is working fine 
Thanks for the advice

**Comment by tresf** [comment]
> @tresf After upgrading to adopt jdk 11 and QZ tray version 2.1.4, printing is working fine
> Thanks for the advice

@sanojmathew thanks, although I'd like to get to the bottom of what's causing this issue.  I'll run some local tests against Java 8u301 and see what I can find.
