### ISSUE TITLE
Windows installer doesn't resume after installing Java

### ISSUE THREAD

**Issue by klabarge** [qzind/tray#938]
**OS:** Windows 10
**Java:** Adoption 11.0.14

The installer won't resume after installing Java for the first time.

This is the same issue as https://github.com/qzind/tray/issues/455

**Comment by tresf** [comment]
Which version of QZ Tray?

**Comment by tresf** [comment]
Answering myself, 2.2 has it bundled, so this must be in regards to 2.1.

**Comment by tresf** [comment]
@klabarge can you try to add `Call FindJava` just before this line and see if it fixes it?

https://github.com/qzind/tray/blob/656eea6c518bb91b8639d31826c9f4f71eda38a1/ant/windows/windows-installer.nsi.in#L64

**Comment by tresf** [comment]
> @klabarge can you try to add `Call FindJava` just before this line and see if it fixes it? It appears we never re-crawl the registry afterward.
> 
> https://github.com/qzind/tray/blob/656eea6c518bb91b8639d31826c9f4f71eda38a1/ant/windows/windows-installer.nsi.in#L64

Nevermind, I was reading my goto's wrong.  The logic is fine.

Upon further investigation, it turns out that Eclipse went and changed their vendor name.  We'll have to search for it under both names now. 

Reference:
* https://github.com/adoptium/installer/pull/347

Related:
* https://github.com/MultiMC/Launcher/issues/4200

I'll add yet another search for this runtime. :)

**Comment by klabarge** [comment]
Tested, works
