### ISSUE TITLE
Magnetic stripe reader Support

### ISSUE THREAD

**Issue by haipt17** [qzind/tray#957]
Hello,

I am trying to integrate MSR213U.

In qz demo page, I used HID methods, I got output like that: 00,00,00,01,4f,26,00,00.

How can I get output like that 

`%BNNNNNNNNNNNNNNNN^DOE/JOHN
^1210201901000101000100061000000?;NNNNNNNNNNNNNNNN=12102019010106111001?`

![image](https://user-images.githubusercontent.com/22137804/162922038-b6387b46-8531-4553-b188-f7a273f49bac.png)

**Comment by tresf** [comment]
@haipt17, can you please provide a user manual for this?  I'm aware that most magnetic swipe readers (MSR) support Keyboard Emulation which should work without QZ Tray.

Your output suggests that you are limited to 8 bytes, likely due to:

```
   ... 
   return qz.hid.readData(hid.vendor, hid.product, '8');
```

I would recommend that you continue to read bytes until you receive the full output from your device.

We would also we willing to write a wiki for this device if you are willing to mail one to our lab.

**Comment by haipt17** [comment]
I found MRS document, increase to 512 bytes.

For anyone got same problem like me

HID output data is array

> List of (hexadecimal) bytes received from the HID device.

Step 1: Convert hex data to text (ascii)
Step 2: Parse text data with regex, output is

` return {
            exp_month: "",
            exp_year: "",
            number: "",
            name: ""
        };`

@tresf , thank you for your support.
