### ISSUE TITLE
Zebra ZT230

### ISSUE THREAD

**Issue by Catsher** [qzind/tray#973]
Direct print from Windows working perfectly, but print throuhg QZ, 2.15 or 2.20 doesn't matter, don't work. I can see in print queue task for a second and then it disappear without printing. ZPL & ZPLII same problem. Help me please.

**Comment by tresf** [comment]
Thank you for sharing the logs.  The logs suggest that you are sending EPL data to the ZT230.  The EPL data looks OK.  Some of the data is corrupted by the log writer, I assume these are just some UTF-8 characters that couldn't be displayed by the logger.

```
N
FK"*"
FK"LABEL1"
FS"LABEL1"
D12
S3
Q200,10
q376
I8,C,001
A37,9,0,1,1,1,N,"���� ���36_�1662846"
A37,31,0,1,1,1,N,"��� �. �. 03.07.71"
A37,53,0,2,1,1,N,"���������� ��������/���������� ��"
A37,75,0,2,1,1,N,"�����������: ��� (����������)"
B100,97,0,1,2,6,60,N,"907225032901"
A60,164,0,3,1,1,N,"907225032901 24.05"
FE
FR"LABEL1"
P1
```

Assuming the above is correct, the most likely cause of the problem is that the printer cannot interpret these EPL commands.  Researching the ZT230 suggests it can interpret EPL just fine, so I have a feeling that something is wrong with the configuration on your machine.

When you installed the driver, did it offer you multiple driver options for the ZT230?  If so, did you select ZPL or EPL?

Since the above commands bypass the printer driver, it's possible that the wrong driver caused this.  I would recommend escalating this issue to Zebra support if the above advice doesn't work, I can't find much in the manual for the ZT230 to suggest how to get it to print in EPL mode.

**Comment by tresf** [comment]
Hmm... Ok, further research shows that the EPL support is firmware-dependant.... can you please read this article? https://www.zebra.com/us/en/support-downloads/knowledge-articles/zt-series-printers-support-epl-language-starting-with-version-v72-17-5z.html

**Comment by Catsher** [comment]
Yes, it's an issure. EPL driver don't work. Command from instruction than mean to change language to "EPL+ZPL" do nothing too. Problem with Zebra itself.
