### ISSUE TITLE
QZ tray is unable to download and print.

### ISSUE THREAD

**Issue by tapu611** [qzind/tray#983]
QZ tray is unable to download shiping label from amazon and flipkart and unable to print on thermal paper. I have downloaded Qz tray for printing thermal paper but unable to do that. I am using Windows7 Laptop.

**Comment by tresf** [comment]
Hi,

Since your issues are specific to Flipkart and Amazon, you must reach out to their respective technical support teams to escalate.

The reason for this is because there are many factors that can prevent "download shipping label [... and ...]print on thermal paper".

Possible causes:

- Local proxy connection
- Incorrect printer driver
- Incompatible printer
- Other software error

A good baseline for testing if QZ Tray is working locally is:
1. Visit https://demo.qz.io
2. Search for your printer
3. Using the "Pixel" tab, print a PDF

If this PDF does not print, the logs from the machine would be helpful in determining the cause.

Note, similar steps should already have been provided by the technical support department of the software you are using and Flipkart/Amazon must be your first line of support when escalating general issues.

If your issues are not general issues (specific error messages), please share these, usually in the form of logs.

**Comment by tresf** [comment]
Closing due to lack of response.
